import { esc,icon,dateText } from './ui.js';
import { storageUsage } from './corpus.js';
import { activities, places, equipmentLabels, bodyRegions, phases, tiers, systems } from './catalog.js';
import { CATEGORIES, IMPACTS, PLANNING_USES } from './personal-activities.js';
import { USES } from './activity-uses.js';
import { SELF_CHECK_TASKS, SELF_CHECK_RESULTS, STOP_RULE, selfCheckHistory, resultText } from './self-check.js';
import { LOAD_BASES,FEELINGS,setsText,weightReference,lastLoad,isLoaded,timeTarget } from './training.js';
import { abilityDimensions,abilitySignals,abilitySides,abilityAreas,abilityUses,abilitySources,activeAssessments,abilityGroup,allowedUses } from './abilities.js';
export const activityName=i=>i.activitySnapshot?.name||activities.find(a=>a.id===i.activityId)?.name||i.customName||'未命名动作';
export function recordedSetsHTML(item){
  return (item.actualSetDetails||[]).map((x,n)=>`<div class="set-line"><span>第 ${n+1} 组</span><strong>${esc(setsText([x]))}</strong><span>${x.loadKg!=null?esc(LOAD_BASES[x.loadBasis]||'重量口径未注明'):''}${x.feeling?` · ${esc(FEELINGS[x.feeling]||'')}`:''}</span></div>`).join('');
}
export function exerciseLogForm(item,state){
  const a=activities.find(a=>a.id===item.activityId);
  // Pre-fill from the last recorded set (and planned reps) so you only change what differs; never auto-increases.
  const prev=lastLoad(a,state);
  const basis=prev?.loadBasis||'unknown';
  const repsPrefill=prev?.reps??Number(String(item.prescription?.reps||'').match(/\d+/)?.[0])??'';
  // 只有负重动作(哑铃/杠铃/器械等)才显示公斤数与重量口径;活动度、自重、心肺动作不问重量。
  const weightRow=isLoaded(a)?`<div class="field-row"><label>本组重量（kg，可选）<input name="loadKg" type="number" min="0" max="500" step="0.1" inputmode="decimal" placeholder="填实际使用的" value="${prev?.loadKg??''}"></label><label>重量口径<select name="loadBasis">${Object.entries(LOAD_BASES).map(([v,l])=>`<option value="${v}" ${v===basis?'selected':''}>${l}</option>`).join('')}</select></label></div>`:'';
  return `<p class="muted">${esc(weightReference(a,state).text)}</p><div class="set-history">${recordedSetsHTML(item)||'<p class="small muted">本次还没有记录组次。</p>'}</div><form id="set-form" data-item="${item.id}">${weightRow}<div class="field-row"><label>本组次数（可选）<input name="reps" type="number" min="1" max="1000" inputmode="numeric" value="${repsPrefill||''}"></label><label>保持秒数（可选）<input name="seconds" type="number" min="1" max="7200" inputmode="numeric"></label></div><label>本组感觉<select name="feeling"><option value="">暂不填写</option>${Object.entries(FEELINGS).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><button class="primary full" type="submit">保存本组 ${icon('check')}</button></form><p class="helper left">默认填的是上次数据，只改这次变化的部分；不把建议重量或计划组数当作实际完成。</p>`;
}
// 计时/保持型动作的进行中卡:大按钮起「准备倒数 → 计时」,到点提示;手动记录折进备选。
export function timedCard(item,state){
  const a=activities.find(a=>a.id===item.activityId);
  const t=timeTarget(item);
  const rounds=item.prescription?.sets||1;
  const done=(item.actualSetDetails||[]).length;
  const roundText=rounds>1?`第 ${Math.min(done+1,rounds)} / ${rounds} 回合`:'';
  const targetText=t?(t.countdown?`保持 ${t.min} 秒`:`${t.min}–${t.max} 秒`):'自己计时，停止时记录用时';
  const restText=item.prescription?.restSeconds?` · 回合间休息 ${item.prescription.restSeconds} 秒`:'';
  return `<div class="timed-card"><p class="timed-target">${esc(targetText)}${roundText?` · ${roundText}`:''}${restText}</p>`
    +`<div class="set-history">${recordedSetsHTML(item)||'<p class="small muted">还没有计时记录。</p>'}</div>`
    +`<button class="primary full timed-start" data-timer="${item.id}">${icon('play')} ${done>=rounds&&rounds>1?'再来一回合':'开始计时'}</button>`
    +`<details class="timed-manual"><summary>改用手动记录</summary>${exerciseLogForm(item,state)}</details>`
    +`<p class="helper left">到点会有提示（可静音）；保持中如有疼痛立即停止。</p></div>`;
}
export function sessionEditForm(s){
  return `<form id="session-form" data-id="${s.id}"><div class="field-row"><label>实际分钟<input name="actualMinutes" type="number" min="1" max="1440" value="${s.actualMinutes??''}"></label><label>费力程度<input name="effort" type="number" min="1" max="10" value="${s.effort??''}"></label></div>${s.items.map(i=>`<fieldset class="edit-record-item"><legend>${esc(activityName(i))} · ${i.status==='completed'?'已完成':'已跳过'}</legend>${recordedSetsHTML(i)}<label>修改组次<input name="sets_${i.id}" value="${esc(setsText(i.actualSetDetails||[]))}" placeholder="如 20kg×10、20kg×8"></label><label>这个动作的感受<textarea name="note_${i.id}" maxlength="2000">${esc(i.feedback||'')}</textarea></label>${i.sourceText?`<p class="small muted">来源原文：${esc(i.sourceText)}</p>`:''}</fieldset>`).join('')}<label>整次感受<textarea name="feedback" maxlength="4000">${esc(s.feedback||'')}</textarea></label><button class="primary" type="submit">保存修改</button></form>`;
}
export function assessmentForm(){
  return `<p class="muted">先记录事实，不自动换算成强弱评分。照片不是必需项，也不能单独证明肌肉无力或疼痛原因。</p><form id="assessment-form"><label>能力维度<select name="dimension">${Object.entries(abilityDimensions).map(([v,x])=>`<option value="${v}">${x.label}</option>`).join('')}</select></label><label>日期<input name="date" type="date" required value="${new Date().toLocaleDateString('en-CA')}"></label><label>信息来源<select name="source"><option value="self_report">我的感受</option><option value="measurement">实际测量 / 设备记录</option><option value="professional">专业人员评估</option></select></label><label>测量或观察方式<input name="method" maxlength="200" placeholder="例如：同一器械、同一动作版本；步行路线"></label><label>是否用于推荐<select name="recommendationUse">${Object.entries(abilityUses).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>结果与感受<textarea name="note" required maxlength="4000" placeholder="例如：今天同样路线走了20分钟，能正常交谈；或记录专业评估结论"></textarea></label><p class="helper left">不要求极限测试。有不适时停止自行测试，记录情况即可。</p><button class="primary full" type="submit">保存能力观察</button></form>`;
}
const options=(dict,selected,keys=Object.keys(dict))=>keys.map(v=>`<option value="${v}" ${v===selected?'selected':''}>${esc(typeof dict[v]==='string'?dict[v]:dict[v].label)}</option>`).join('');
const abilityMeta=a=>[abilitySignals[a.signal]&&a.signal!=='unknown'?abilitySignals[a.signal]:'',(a.bodyAreas||[]).map(x=>abilityAreas[x]).join('、'),a.side&&a.side!=='not_applicable'?abilitySides[a.side]:'',a.context,abilitySources[a.source]||'',a.method].filter(Boolean).join(' · ');
const ABILITY_GROUPS=[['review','需专业确认','不自动安排训练。请咨询医生或康复专业人员，确认可以训练后归档或改为「仅保存」。'],['ok','目前顺畅','可作为基础；设为「温和参考」时，同类动作可能稍微靠前。'],['watch','值得留意','只作为偏向温和活动的参考，不作病因判断。'],['other','其他记录','早先的手记，没有分类，仅保存。']];
function abilityCard(s,a,active=true){
  const raw=a.evidenceIds?.map(id=>(s.abilityEvidence||[]).find(e=>e.id===id)).find(Boolean);
  return `<article class="ability-entry"><strong>${esc(abilityDimensions[a.dimension]?.label||a.dimension)} · ${dateText(a.observedAt)}${active?'':a.status==='archived'?' · 已归档':' · 已过期'}</strong><p>${esc(a.note)}</p>${abilityMeta(a)?`<p class="small muted">${esc(abilityMeta(a))}</p>`:''}${a.evidenceQuote?`<p class="small">原话：「${esc(a.evidenceQuote)}」</p>`:''}${raw?`<details><summary>查看完整原话</summary><p class="small">${esc(raw.rawText)}</p></details>`:''}<div class="field-row"><label>用途<select data-ability-use="${a.id}">${options(abilityUses,a.recommendationUse,allowedUses(a))}</select></label></div><div class="dialog-actions"><button class="text-button" data-ability-archive="${a.id}">${a.status==='archived'?'恢复':'归档'}</button><button class="text-button" data-ability-delete="${a.id}">删除</button></div></article>`;
}
export function capacityHTML(s){
  const all=s.assessments||[],active=activeAssessments(all),inactive=all.filter(a=>!active.includes(a));
  const groups=ABILITY_GROUPS.map(([id,title,help])=>{const rows=active.filter(a=>abilityGroup(a)===id);return rows.length?`<div class="ability-group ${id}"><h3>${title}（${rows.length}）</h3><p class="small muted">${help}</p>${[...rows].reverse().map(a=>abilityCard(s,a)).join('')}</div>`:'';}).join('');
  return `<section class="card capacity"><div class="section-heading"><h2>个人能力记录</h2><button class="text-button" data-action="assessment">${icon('plus')} 手动记一次</button></div><p class="muted">用自己的话说说最近的身体和运动情况，AI 会整理成几条观察，逐条确认后才保存。没有记录就不猜分数。</p><button class="primary full" data-action="ability-intake">让 AI 整理我的身体与能力情况 ${icon('arrow')}</button>${selfCheckHTML(s)}${groups||'<p class="helper left">还没有有效的观察。</p>'}${inactive.length?`<details><summary>已归档或过期（${inactive.length}）</summary>${[...inactive].reverse().map(a=>abilityCard(s,a,false)).join('')}</details>`:''}<p class="helper left">只有设为「温和参考」的观察会发给 AI 参与安排，而且只影响已通过安全过滤的动作顺序；「需专业确认」会暂停自动安排。照片/视频暂未接入。</p></section>`;
}
export function abilityIntakeForm(p={}){
  const today=new Date().toLocaleDateString('en-CA');
  return `<form id="ability-intake-form"><label>告诉我你最近的身体和运动情况<textarea name="rawText" required maxlength="4000" rows="7" placeholder="可粘贴一段话、体测报告文字、医生或教练的限制、手表摘要。例如：久坐后右侧髋前面紧，深蹲到底不舒服；羽毛球启动慢；上周睡眠 6 小时。">${esc(p.rawText||'')}</textarea></label><div class="field-row"><label>资料类型<select name="source">${options(abilitySources,p.source||'self_report')}</select></label><label>大约发生在<input type="date" name="observedOn" required max="${today}" value="${esc(p.observedOn||today)}"></label></div><p class="helper left">这段文字会发给你启用的 AI 服务。AI 只整理和追问、不诊断；整理结果逐条确认后才保存。附件暂未接入。</p><button class="primary full" type="submit">开始整理 ${icon('arrow')}</button></form>`;
}
export function abilityConfirmForm(p){
  const today=new Date().toLocaleDateString('en-CA');
  return `${p.warnings?.length?`<div class="notice error">${p.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}</div>`:''}<p class="helper left">默认「仅保存」。只有你改成「温和参考」的条目才会参与安排；不需要的条目取消勾选即可，不会保存。</p><form id="ability-confirm-form">${p.drafts.map((d,n)=>`<fieldset class="log-session"><legend><label class="checkbox-line"><input type="checkbox" name="keep_${n}" checked> 第 ${n+1} 条</label></legend><p class="small">原话：「${esc(d.evidenceQuote)}」</p><div class="field-row"><label>维度<select name="dimension_${n}">${options(abilityDimensions,d.dimension)}</select></label><label>观察<select name="signal_${n}">${options(abilitySignals,d.signal)}</select></label></div><div class="equipment-checks">${Object.entries(abilityAreas).map(([v,l])=>`<label class="check-pill"><input type="checkbox" name="area_${n}" value="${v}" ${d.bodyAreas.includes(v)?'checked':''}>${l}</label>`).join('')}</div><div class="field-row"><label>左右<select name="side_${n}">${options(abilitySides,d.side)}</select></label><label>日期<input type="date" name="observedAt_${n}" required max="${today}" value="${esc(d.observedAt)}"></label></div><label>情境<input name="context_${n}" maxlength="100" value="${esc(d.context)}" placeholder="例如：久坐后、深蹲到底时"></label><label>说明<textarea name="note_${n}" required maxlength="300">${esc(d.note)}</textarea></label><label>用途${d.recommendationUse==='gentle_preference'?'<span class="small muted">（AI 建议：温和参考）</span>':''}<select name="use_${n}">${options(abilityUses,'off',allowedUses(d))}</select></label></fieldset>`).join('')}<button class="primary full" type="submit">保存勾选的观察 ${icon('check')}</button><button class="secondary full" type="button" data-action="ability-retry">回到原文修改</button></form>`;
}
// 动作单元字段（手动添加、编辑、AI 草稿确认共用）。p 是字段名前缀，d 是已有值。
const checks=(name,dict,selected=[],label=x=>typeof x==='string'?x:x.label)=>`<div class="equipment-checks">${Object.entries(dict).map(([v,x])=>`<label class="check-pill"><input type="checkbox" name="${name}" value="${v}" ${selected.includes(v)?'checked':''}>${esc(label(x))}</label>`).join('')}</div>`;
const sel=(name,dict,value)=>`<select name="${name}">${Object.entries(dict).map(([v,x])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${esc(typeof x==='string'?x:x.label)}</option>`).join('')}</select>`;
export function activityFields(p,d={}){
  const list=v=>esc((v||[]).join('\n'));
  return `<label>动作名称<input name="${p}name" required maxlength="40" value="${esc(d.name||'')}"></label><label>别名（可选，每行一个）<textarea name="${p}aliases" rows="1" maxlength="160">${list(d.aliases)}</textarea></label><label>怎么做（一句话）<textarea name="${p}description" rows="2" maxlength="200">${esc(d.description||'')}</textarea></label><div class="field-row"><label>类别${sel(p+'category',CATEGORIES,d.category||'mobility')}</label><label>阶段${sel(p+'phase',phases,d.phase||({mobility:'warmup',recovery:'cooldown'}[d.category||'mobility']||'main'))}</label></div><fieldset><legend>主要训练部位（力量动作必选）</legend>${checks(p+'primaryRegions',bodyRegions,d.primaryRegions)}</fieldset><fieldset><legend>场地</legend>${checks(p+'places',places,d.places||['home','gym'])}</fieldset><fieldset><legend>需要的器械（不需要就都不选）</legend>${checks(p+'equipment',equipmentLabels,d.equipment)}</fieldset><div class="field-row"><label>难度${sel(p+'tier',tiers,d.tier||1)}</label><label>冲击${sel(p+'impact',IMPACTS,d.impact||'low')}</label></div><div class="field-row"><label>通常占几分钟<input name="${p}minutes" type="number" min="1" max="30" value="${d.minutes||3}"></label><label>体系${sel(p+'system',systems,d.system||'general')}</label></div><label>起始姿势（可选，每行一条）<textarea name="${p}setup" rows="2">${list(d.setup)}</textarea></label><label>动作步骤（每行一步）<textarea name="${p}steps" rows="3">${list(d.steps)}</textarea></label><label>要点（可选，每行一条）<textarea name="${p}cues" rows="2">${list(d.cues)}</textarea></label><label>常见错误（可选，每行一条）<textarea name="${p}mistakes" rows="2">${list(d.mistakes)}</textarea></label><label>参考练习量（可选，照原文写，不确定就留空）<input name="${p}dose" maxlength="100" value="${esc(d.dose||'')}"></label>`;
}
// AI 从内容里提取的动作：已有动作可记用途，变式 / 新动作逐项编辑后保存为「我的动作」。
export function activityIntakeForm(r,nameOf,preview=null){
  const useSel=(n,u)=>`<div class="field-row"><label>用途<select name="use_${n}"><option value="">不记用途</option>${Object.entries(USES).map(([v,l])=>`<option value="${v}" ${u?.use===v?'selected':''}>${l}</option>`).join('')}</select></label><label>部位<select name="region_${n}"><option value="">不指定</option>${Object.entries(bodyRegions).map(([v,x])=>`<option value="${v}" ${u?.region===v?'selected':''}>${esc(x.label)}</option>`).join('')}</select></label></div><input type="hidden" name="note_${n}" value="${esc(u?.note||'')}">`;
  const image=preview?.thumbnail?`<img class="action-frame-preview" data-frame-capture="${esc(preview.captureId)}" data-frame-segment="${esc(preview.segmentId)}" alt="动作片段代表画面" loading="lazy">`:'';
  const when=preview?` · ${Math.floor(preview.startMs/60000)}:${String(Math.floor(preview.startMs/1000)%60).padStart(2,'0')}–${Math.floor(preview.endMs/60000)}:${String(Math.floor(preview.endMs/1000)%60).padStart(2,'0')}`:'';
  return `${image}${preview?.description?`<p class="small muted">视频画面：${esc(preview.description)}${when}</p>`:''}${r.warnings?.length?`<div class="notice">${r.warnings.map(w=>`<p class="small">${esc(w)}</p>`).join('')}</div>`:''}<p class="helper left">已有的动作不会重复新建，可以给它记个用途；动作库没有的，核对后存为「我的动作」，默认仅手动使用。</p><form id="activity-intake-form">${r.candidates.map((c,n)=>`<fieldset class="log-session"><legend><label class="checkbox-line"><input type="checkbox" name="keep_${n}" checked> ${c.type==='existing'?`动作库已有：${esc(nameOf(c.matchedActivityId))}`:c.type==='variant'?`「${esc(nameOf(c.matchedActivityId))}」的变式`:'新动作'}</label>${c.lowTrust?'<span class="badge warm">依据是 AI 画面描述，待核对</span>':''}</legend><p class="small muted">原文：「${esc(c.evidenceQuote)}」</p>${c.type==='existing'?useSel(n,c.use):`${activityFields(`a${n}_`,c.draft)}<label class="checkbox-line"><input type="checkbox" name="allow_${n}">允许以后自动安排（不勾就只能手动加入）</label>`}</fieldset>`).join('')}<button class="primary full" type="submit">保存勾选的动作 ${icon('check')}</button></form>`;
}
// ---------- 简短自评 ----------
const CHECK_NOTE='动作做法为循动整理，尚未经专业人员核对。只在舒适范围内做，不追求完成数量。';
export function selfCheckHTML(s){
  const rows=selfCheckHistory(s.assessments||[]),any=rows.some(r=>r.latest);
  return `<div class="self-check"><div class="section-heading"><h3>简短自评</h3><span class="small muted">5 项 · 约 3～5 分钟</span></div><p class="small muted">看看哪些动作现在做起来顺畅、哪些值得留意。不打分，也不判断原因；可以跳过任何一项。</p>${any?`<div class="self-check-rows">${rows.map(r=>`<div class="self-check-row"><span>${esc(r.task.title)}</span><strong>${r.latest?`${esc(resultText(r.latest))}${r.latest.discomfort?' · 有不适':''}`:'<span class="muted">还没做过</span>'}</strong>${r.latest?`<small class="muted">${dateText(r.latest.observedAt)}${r.previous?` · 上次 ${esc(resultText(r.previous))}（${dateText(r.previous.observedAt)}）`:''}</small>`:''}</div>`).join('')}</div><p class="helper left">主观感受每天会有波动，对照时看大致趋势即可。</p>`:''}<button class="secondary full" data-action="self-check">${any?'再做一次自评':'做一次简短自评'} ${icon('arrow')}</button></div>`;
}
export function selfCheckTaskForm(t,answer={},index,total){
  const group=(name,label)=>`<fieldset class="check-group"><legend>${label}</legend><div class="equipment-checks">${Object.entries(SELF_CHECK_RESULTS).map(([v,l])=>`<label class="check-pill"><input type="radio" name="${name}" value="${v}" ${answer[name]===v?'checked':''} required>${l}</label>`).join('')}</div></fieldset>`;
  return `<p class="small muted">第 ${index+1} / ${total} 项 · ${esc(CHECK_NOTE)}</p><p>${esc(t.purpose)}</p><ol class="cues">${t.how.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p class="small muted">${esc(t.support)}</p><div class="notice error"><p class="small">${esc(STOP_RULE)}</p></div><form id="self-check-form" data-task="${t.id}">${t.sided?group('left','左侧')+group('right','右侧'):group('both','做起来')}<label class="checkbox-line"><input type="checkbox" name="discomfort" ${answer.discomfort?'checked':''}>做的时候出现了疼痛、麻木、头晕或明显不适（已停止）</label><label>备注（可选）<input name="note" maxlength="300" value="${esc(answer.note||'')}" placeholder="例如：右边举到头顶有点卡"></label><button class="primary full" type="submit">${index+1<total?'下一项':'看看结果'} ${icon('arrow')}</button>${index>0?'<button class="secondary full" type="button" data-action="self-check-prev">上一项</button>':''}</form>`;
}
export function selfCheckSummaryForm(answers){
  const rows=SELF_CHECK_TASKS.map(t=>{const a=answers[t.id];const txt=a?(t.sided?`左 ${SELF_CHECK_RESULTS[a.left]||'—'} · 右 ${SELF_CHECK_RESULTS[a.right]||'—'}`:SELF_CHECK_RESULTS[a.both]||'—'):'跳过';return `<div class="self-check-row"><span>${esc(t.title)}</span><strong>${esc(txt)}${a?.discomfort?' · 有不适':''}</strong></div>`;}).join('');
  return `<div class="self-check-rows">${rows}</div><p class="helper left">只记录你的感受，不换算成分数，也不推断原因。出现过不适的项不会参与安排；如果不适持续或加重，请咨询医生或康复专业人员。</p><form id="self-check-save"><label class="checkbox-line"><input type="checkbox" name="gentle">让「勉强 / 做不到」的项温和参考安排（对应的练习会稍微靠前，不会解锁更难的动作）</label><button class="primary full" type="submit">保存自评 ${icon('check')}</button><button class="secondary full" type="button" data-action="self-check-prev">返回修改</button></form>`;
}
// 主题总结的确认表单：每个主题可整张取消，每条结论可改文字或取消。
export function digestConfirmForm(p,titleOf){
  return `<p class="helper left">AI 按主题归纳了你的知识库。每条结论都附原文出处；同名主题会更新原来那张卡。不需要的主题或结论取消勾选即可。</p><form id="digest-confirm-form">${p.topics.map((t,n)=>`<fieldset class="log-session"><legend><label class="checkbox-line"><input type="checkbox" name="topic_${n}" checked> #${esc(t.topic)}${p.existing.includes(t.topic)?'<span class="badge">更新原卡</span>':'<span class="badge warm">新主题</span>'}</label></legend><label>标题<input name="title_${n}" maxlength="120" value="${esc(t.title)}"></label>${t.principles.map((pr,k)=>`<div class="log-item"><label class="checkbox-line"><input type="checkbox" name="keep_${n}_${k}" checked> 第 ${k+1} 条</label><textarea name="text_${n}_${k}" required maxlength="400">${esc(pr.text)}</textarea>${pr.sources.map(src=>`<p class="small muted">${esc(titleOf(src.knowledgeId)||'来源')}：「${esc(src.quote)}」</p>`).join('')}</div>`).join('')}</fieldset>`).join('')}<button class="primary full" type="submit">保存勾选的主题总结 ${icon('check')}</button></form>`;
}
// 创作者方法卡的逐条确认表单：每条方法都带出处，用户可改文字、取消勾选或删关联动作。
export function methodConfirmForm(p){
  const titleOf=id=>p.cards.find(c=>c.id===id)?.title||'来源知识卡';
  return `${p.warnings?.length?`<div class="notice">${p.warnings.map(w=>`<p class="small">${esc(w)}</p>`).join('')}</div>`:''}<p class="helper left">每条方法都来自这位创作者已确认的知识卡，附逐字出处。可修改文字或取消勾选，至少保留一条。</p><form id="method-confirm-form"><label>方法卡标题<input name="title" required maxlength="120" value="${esc(p.card.title)}"></label><label>概述（可选）<textarea name="summary" maxlength="700">${esc(p.card.summary||'')}</textarea></label>${p.card.principles.map((pr,n)=>`<fieldset class="log-item"><label class="checkbox-line"><input type="checkbox" name="keep_${n}" checked> 保留第 ${n+1} 条</label><label>方法<textarea name="text_${n}" required maxlength="400">${esc(pr.text)}</textarea></label>${pr.sources.map(src=>`<p class="small muted">${esc(titleOf(src.knowledgeId))}：「${esc(src.quote)}」</p>`).join('')}</fieldset>`).join('')}${p.card.activityIds.length?`<fieldset><legend>关联现有动作（可选）</legend>${p.card.activityIds.map((id,n)=>`<label class="checkbox-line"><input type="checkbox" name="link_${n}" value="${esc(id)}" checked> ${esc(activities.find(a=>a.id===id)?.name||id)}</label>`).join('')}</fieldset>`:''}<label>还缺哪些信息（可选，每行一条；只记缺什么，不会当作规则）<textarea name="unknowns" rows="2" maxlength="500">${esc((p.card.unknowns||[]).join('\n'))}</textarea></label><p class="helper left">方法卡不作病因判断，也不能绕过当天的安全与器械限制。</p><button class="primary full" type="submit">保存方法卡 ${icon('check')}</button></form>`;
}
export function privacyHTML(s){return `<section class="card privacy"><h2>数据与 AI</h2><p>记录保存在当前浏览器。主动启用 AI 后，所选服务会收到必要的身体档案、近期记录、心得和你允许参考的收藏；不会后台自动发送。</p><p class="small muted">${s.settings?.aiConsent?'已允许当前服务；可随时关闭。':'AI 数据发送默认关闭。'}</p><div class="dialog-actions"><button class="secondary" data-action="ai-settings">AI 设置</button><button class="secondary" data-action="ingest-settings">自动视频整理</button><button class="secondary" data-action="export">导出备份</button><button class="secondary" data-action="import">恢复备份</button></div><p class="helper left">不同浏览器或地址的记录不自动同步。恢复时合并记录，已有同 ID 内容优先保留。</p><p class="helper left">iPhone：Safari 与「添加到主屏幕」的 App 存储互不相通。请先添加到主屏幕、从主屏幕打开，再在里面恢复备份并重新填写 AI key。</p><p class="small muted">本机存储已用 ${storageUsage(s).text}${storageUsage(s).level==='ok'?'':'，建议先导出备份'}。</p><p class="small muted" data-offline-status>正在检查离线状态…</p></section>`;}
