import { activities, goals, places, equipmentLabels, bodyRegions, regionLabel, systems, tiers } from './catalog.js';
import { capacityHTML,privacyHTML,recordedSetsHTML,exerciseLogForm,timedCard } from './experience.js';
import { weightReference,isTimed } from './training.js';
import { weekSummary, safeURL } from './domain.js';
import { creatorGroups } from './creators.js';
import { pendingDigest } from './digest.js';
import { METHOD_MODES, plannableMethodCards } from './method-plan.js';
import { entryKind, entryTrust, lowTrust, SOURCE_KINDS, TRUST_LEVELS, normalizeTopics, corpusTopics, storageUsage, corpusEntries } from './corpus.js';
import { CONTENT_TYPES, PLAN_POINT_KINDS } from './knowledge.js';
import { esc, icon, badge, dateText, empty, elapsedText } from './ui.js';
export const routes = { today:'今天', records:'训练记录', library:'动作库', knowledge:'知识库', body:'我的身体' };
const getActivity = id => activities.find(a => a.id === id);
const getNote = (s,id) => s.notes.find(n => n.activityId === id)?.text;
export function activityVideoLinksHTML(s,activityId,activity=getActivity(activityId)){
  const rows=[];
  const add=(url,title,startMs=null,endMs=null)=>{const safe=safeURL(url);if(!safe)return;const key=`${safe}|${startMs??''}|${endMs??''}`;if(!rows.some(x=>x.key===key))rows.push({key,url:safe,title,startMs,endMs});};
  if(activity?.source?.sourceUrl)add(activity.source.sourceUrl,'学习来源',activity.source.startMs,activity.source.endMs);
  for(const k of s.knowledge||[]){const link=(k.activityLinks||[]).find(x=>x.activityId===activityId);if(!(k.activityIds||[]).includes(activityId)&&!link)continue;const capture=(s.captures||[]).find(c=>c.knowledgeId===k.id);add(capture?.rawUrl||k.url,k.title,link?.startMs,link?.endMs);}
  if(!rows.length)return '';
  const time=ms=>ms==null?'':`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
  return `<div class="activity-video-links"><span class="small muted">练习参考（原视频需自行核对）</span>${rows.map(x=>`<a class="text-button" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">打开${esc(x.title==='学习来源'?'学习来源视频':'来源视频')}${x.startMs!=null?` · ${time(x.startMs)}${x.endMs!=null?`–${time(x.endMs)}`:''}`:''} ${icon('arrow')}</a>`).join('')}</div>`;
}
const heading = (eyebrow,title,sub,aside='') => `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}<span class="orange">。</span></h1><p>${sub}</p></div>${aside}</div>`;
export function shell(page,state,content,error=false) {
  const nav=(mobile=false)=>Object.entries(routes).map(([id,label])=>`<button class="nav-item ${page===id?'active':''}" data-nav="${id}" ${page===id?'aria-current="page"':''}>${icon(id)}<span>${mobile&&id==='records'?'记录':mobile&&id==='body'?'身体':label}</span></button>`).join('');
  return `<aside class="sidebar"><a class="brand" href="#today"><img src="/icon.svg" alt=""/><span>循动<small>MOVE WITH YOUR LIFE</small></span></a><div class="nav-caption">我的运动空间</div><nav aria-label="主要导航">${nav()}</nav><div class="sidebar-bottom"><div class="local-indicator">${icon('bookmark')}<div>你的私人练习簿<small>仅保存在当前浏览器</small></div></div><button class="text-button" data-action="export">${icon('download')} 导出我的记录</button><div class="version">界面原型 · v0.1</div></div></aside>
  <main><header class="topbar"><span class="breadcrumb">我的运动空间 <span>/</span> ${routes[page]}</span><span class="topdate">${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span><button class="avatar" data-nav="body" aria-label="打开我的身体档案">${esc(state.profile.name.slice(0,1)||'我')}</button></header><div class="content">${error?'<div class="notice error">本地记录读取异常。已暂停保存，原始数据未被覆盖。</div>':''}${content}</div></main><nav class="bottom-nav" aria-label="手机导航">${nav(true)}</nav>`;
}
export function todayHTML(s,r,ai={}) {
  const summary=weekSummary(s.sessions);
  return `${heading('A LITTLE MOVEMENT, EVERY DAY','今天，动一点','从现在有的时间开始，找到适合今天的节奏。',`<span class="heading-icon">${icon('sun')}</span>`)}<div class="today-grid"><div class="primary-column">${s.draft?planHTML(s,ai):plannerHTML(s,r,ai)+savedPlansHTML(s)}
  <section class="section"><div class="section-heading"><h2>从生活里的小空隙开始</h2><span>无需等到有空的一天</span></div><div class="quick-grid">
  <button class="quick-card peach" data-preset="office"><span class="quick-icon">${icon('office')}</span><strong>工作间隙</strong><span>离开椅子，活动一下</span><footer>5 分钟 ${icon('arrow')}</footer></button>
  <button class="quick-card lavender" data-preset="mobility"><span class="quick-icon">${icon('mobility')}</span><strong>舒展身体</strong><span>留一点时间给活动度</span><footer>10 分钟 ${icon('arrow')}</footer></button>
  <button class="quick-card blue" data-preset="recovery"><span class="quick-icon">${icon('recovery')}</span><strong>慢下来</strong><span>呼吸、离屏、轻松走动</span><footer>5 分钟 ${icon('arrow')}</footer></button></div></section></div>
  <aside class="right-column"><section class="card weekly"><div class="section-heading"><h2>最近 7 天</h2>${icon('today')}</div><div class="stats"><div><strong>${summary.sessions}</strong><span>次已记录训练</span></div><div><strong>${summary.minutes}<small> min</small></strong><span>已填写的实际时长</span></div></div><div class="week-strip">${Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const did=s.sessions.some(s=>new Date(s.endedAt).toDateString()===d.toDateString());return `<div class="day ${did?'did':''} ${i===6?'current':''}"><span>${['日','一','二','三','四','五','六'][d.getDay()]}</span><b>${did?icon('check'):d.getDate()}</b></div>`;}).join('')}</div><p class="muted small">${summary.unknown?`${summary.unknown} 次训练未填写时长。`:'只统计你确认完成的训练。'}${summary.sessions?'':'第一次记录，从今天开始。'}</p><button class="text-button" data-nav="records">查看训练记录 ${icon('arrow')}</button></section>
  <section class="card body-prompt"><span class="overline">先听听身体的声音</span><h2>今天感觉怎么样？</h2><p>睡眠、疲劳和不舒服的地方，都可以慢慢记下来。</p><button class="secondary full" data-action="observation">${icon('plus')} 记一下身体状态</button></section>${s.notes.length?`<section class="notebook"><span class="overline">来自你的练习簿</span><p>「${esc(s.notes.at(-1).text)}」</p><button class="text-button" data-detail="${s.notes.at(-1).activityId}">查看我的心得 ${icon('arrow')}</button></section>`:`<section class="notebook"><span class="overline">让下次练习更顺手</span><p>给一个动作写下自己的发力提示和感受。</p><button class="text-button" data-nav="library">打开动作库 ${icon('arrow')}</button></section>`}</aside></div><p class="prototype-note">记录默认留在本机；AI 仅在你启用并主动请求时发送数据。尚未连接健康设备。</p>`;
}
// 我收藏的训练：点「载入」会用今天的状态重新检查，再生成一份可调整的安排。
function savedPlansHTML(s) {
  const rows=s.savedPlans||[];if(!rows.length)return '';
  return `<section class="section saved-plans"><div class="section-heading"><h2>我收藏的训练</h2><span>载入时按今天的状态重新检查</span></div>${[...rows].reverse().map(t=>`<div class="saved-plan card"><div class="saved-plan-main"><strong>${esc(t.name)}</strong><span class="small muted">${t.items.length} 个动作 · ${t.request.minutes} 分钟 · ${places[t.request.place]||''}${t.useCount?` · 练过 ${t.useCount} 次，上次 ${dateText(t.lastUsedAt)}`:''}</span></div><div class="saved-plan-actions"><button class="primary" data-load-template="${esc(t.id)}">载入 ${icon('arrow')}</button><button class="text-button" data-rename-template="${esc(t.id)}">重命名</button><button class="text-button" data-delete-template="${esc(t.id)}">删除</button></div></div>`).join('')}</section>`;
}
function planFocus(request) {
  return request.focus==='strength' && request.targetRegions?.length ? `力量 · ${regionLabel(request.targetRegions)}` : goals[request.focus];
}
function strengthSelector(r) {
  const selected=r.targetRegions||[];
  const choice=([id,region])=>`<button type="button" class="region-choice ${selected.includes(id)?'selected':''}" data-region="${id}" aria-pressed="${selected.includes(id)}"><span>${region.label}</span>${selected.includes(id)?icon('check'):''}</button>`;
  return `<fieldset class="strength-selector"><legend>今天想练哪些部位？<span>可多选</span></legend><button type="button" class="region-all ${selected.length?'':'selected'}" data-region="all" aria-pressed="${!selected.length}">${icon('today')} 全身均衡，帮我安排${!selected.length?icon('check'):''}</button><div class="region-grid" role="group" aria-label="常用训练部位">${Object.entries(bodyRegions).filter(([,v])=>v.common).map(choice).join('')}</div><details id="region-more" ${selected.some(id=>!bodyRegions[id]?.common)?'open':''}><summary>更多部位<span>前臂、足踝、颈部</span></summary><div class="region-extra" role="group" aria-label="更多训练部位">${Object.entries(bodyRegions).filter(([,v])=>!v.common).map(choice).join('')}</div></details><p class="region-hint">${selected.length?selected.map(id=>`${bodyRegions[id].label}：${bodyRegions[id].detail}`).join('；'):'不确定就保留全身均衡；有重点时，先选 1～2 项即可。'}</p>${selected.includes('neck')?'<p class="region-caution">颈部目前没有可自动推荐的力量动作，系统会保留这一内容缺口。</p>':''}</fieldset>`;
}
function methodReportHTML(p) {
  if(p.methodHint)return `<div class="method-report muted">已选「${esc(p.methodHint.title)}」· ${esc(p.methodHint.modeLabel)}，但这次是本地规则安排，没有按方法编排。想按方法安排，请用「给我安排」并启用 AI。</div>`;
  if(!p.methodReport)return '';
  const r=p.methodReport,m=p.methodPreference;
  return `<div class="method-report"><strong>按「${esc(m.title)}」· ${esc(m.modeLabel)}</strong>${r.adopted.length?`<p><span>采用了</span>${r.adopted.map(esc).join('；')}</p>`:''}${r.skipped.length?`<p><span>没采用</span>${r.skipped.map(x=>`${esc(x.text)}（${esc(x.reason)}）`).join('；')}</p>`:''}${r.filledByDefault?`<p><span>常规补齐</span>${esc(r.filledByDefault)}</p>`:''}</div>`;
}
function regionCoverageHTML(plan) {
  if(!plan.regionCoverage?.length)return '';
  const included=plan.regionCoverage.filter(x=>x.status==='included').map(x=>x.id);
  const missing=plan.regionCoverage.filter(x=>x.status==='unavailable').map(x=>x.id);
  const limited=plan.regionCoverage.filter(x=>x.status==='time_limited').map(x=>x.id);
  return `<div class="region-coverage"><p>本次主要训练：${regionLabel(included)||'暂无'}</p>${missing.length?`<p class="muted">尚未匹配：${regionLabel(missing)}（场地、器械或动作库限制）</p>`:''}${limited.length?`<p class="muted">本次时间内未安排：${regionLabel(limited)}</p>`:''}<span>这是计划覆盖，不代表已经完成训练。</span></div>`;
}

// 按创作者方法安排：只列出用户已允许参与安排的方法卡；「参考我的知识库」关掉时不生效。
function methodPickerHTML(s,ai={}) {
  const cards=plannableMethodCards(s),pref=s.settings?.methodPreference||{};
  if(!cards.length)return (s.creatorProfiles||[]).length?'<p class="helper left">想按某位创作者的方法安排，先在知识库里给方法卡打开「用于安排参考」。</p>':'';
  const selected=cards.some(c=>c.id===pref.creatorProfileId)?pref.creatorProfileId:'';
  return `<div class="method-picker"><div class="field-row"><label>按创作者方法安排<select id="method-card"><option value="">不使用（只浏览）</option>${cards.map(c=>`<option value="${esc(c.id)}" ${selected===c.id?'selected':''}>${esc(c.title)}</option>`).join('')}</select></label><label>采用程度<select id="method-mode" ${selected?'':'disabled'}>${Object.entries(METHOD_MODES).map(([v,m])=>`<option value="${v}" ${(pref.mode||'inspiration')===v?'selected':''}>${m.label}</option>`).join('')}</select></label></div>${selected?`<p class="helper left">${esc(METHOD_MODES[pref.mode||'inspiration'].rule)}${s.settings?.useCorpus===false?' 现在「参考我的知识库」关着，这次不会生效。':''}${ai.ready?'':' 按方法编排需要 AI；本地规则只会提示，不按方法编排。'}</p>`:''}</div>`;
}
function planningReferencesHTML(s) {
  const saved=corpusEntries(s),summaries=[...(s.creatorProfiles||[]).filter(p=>p.status==='saved').map(p=>({id:p.id,title:p.title,type:'创作者方法'})),...(s.topicCards||[]).filter(p=>p.status==='saved').map(p=>({id:p.id,title:p.title,type:'主题总结'}))];
  const refs=[...saved.map(k=>({id:k.id,title:k.title,type:k.contentType==='training_plan'?'训练方案':k.contentType==='follow_along'?'跟练视频':'知识卡',source:k.source.name,trust:lowTrust(k.trust)})),...summaries];
  if(!refs.length)return '';
  const prefs=s.settings?.planningReferences||{},mode=prefs.mode||(s.settings?.useCorpus===false?'none':'auto'),selected=new Set(prefs.selectedIds||[]);
  const choices=[['auto','自动挑选','按今天目标，从已允许参考的资料里挑相关内容'],['selected','我选资料','只发送下面勾选的资料；勾选即本次确认使用'],['none','不参考','只根据今天的状态和动作库安排']];
  return `<fieldset class="planning-references"><legend>本次参考资料</legend><div class="reference-modes" role="radiogroup" aria-label="本次参考资料方式">${choices.map(([v,label,hint])=>`<label class="reference-mode"><input type="radio" name="reference-mode" value="${v}" data-reference-mode ${mode===v?'checked':''}><span><strong>${label}</strong><small>${hint}</small></span></label>`).join('')}</div><details class="reference-list" ${mode==='selected'?'open':''}><summary>选择具体资料 <span>${selected.size?`已选 ${selected.size} 条`:'可选'}</span></summary>${refs.length?`<div class="reference-options">${refs.map(x=>`<label class="reference-option"><input type="checkbox" data-reference-id="${esc(x.id)}" ${selected.has(x.id)?'checked':''}><span><strong>${esc(x.title)}</strong><small>${esc(x.type)}${x.source?` · ${esc(x.source)}`:''}${x.trust?' · AI 画面整理，待核对':''}</small></span></label>`).join('')}</div><p class="small muted">只会把已确认的知识卡 / 总结卡发送给 AI。待整理草稿不会进入训练建议。</p>`:''}</details></fieldset>`;
}
function plannerHTML(s,r,ai={}) {
  return `<section class="card planner"><div class="planner-top"><div><span class="overline">留给自己的时间</span><h2>现在，想动多久？</h2></div><div class="duration-display"><strong>${r.minutes}</strong><span>分钟</span></div></div><div class="duration-options" role="group" aria-label="运动时间">${[5,10,20,30,45,60].map(n=>`<button data-minutes="${n}" class="${r.minutes===n?'selected':''}" aria-pressed="${r.minutes===n}">${n}<small>分</small></button>`).join('')}</div>
  <div class="planner-fields"><div class="place-options" role="group" aria-label="训练地点">${Object.entries(places).map(([id,label])=>`<button data-place="${id}" class="${r.place===id?'selected':''}" aria-pressed="${r.place===id}">${icon(id)}${label}</button>`).join('')}</div>
  ${ai.ready?`<label class="ai-box">说说今天想怎么练（可选）<textarea id="ai-text" maxlength="1000" rows="2" placeholder="例如：想练上肢，今天只有哑铃">${esc(ai.text||'')}</textarea></label>`:''}
  ${planningReferencesHTML(s)}
  ${(s.creatorProfiles||[]).some(p=>p.allowedInPlanning)?`<details class="advanced-method"><summary>高级：按某位创作者的方法安排</summary>${methodPickerHTML(s,ai)}</details>`:''}
  <button class="primary full" data-action="generate-smart" ${ai.busy?'disabled':''}>${ai.busy?'正在安排…':`给我安排 ${icon('arrow')}`}</button>
  <p class="helper">${ai.ready&&s.settings?.aiConsent?'使用 AI 辅助；必要时可切换本地规则。':'当前使用本地规则，不发送身体记录。'}</p>
  <details id="planning-options" ${ai.optionsOpen?'open':''}><summary>调整重点、部位与状态 <span>${goals[r.focus]}</span></summary><div class="advanced-options"><div class="field-row"><label>今天想侧重<select id="focus">${Object.entries(goals).map(([id,l])=>`<option value="${id}" ${r.focus===id?'selected':''}>${l}</option>`).join('')}</select></label><label>当前状态<select id="readiness"><option value="normal" ${r.readiness==='normal'?'selected':''}>状态还不错</option><option value="tired" ${r.readiness==='tired'?'selected':''}>有点疲惫</option><option value="discomfort" ${r.readiness==='discomfort'?'selected':''}>身体有不舒服</option></select></label></div>${r.focus==='strength'?strengthSelector(r):''}<div class="equipment-line">${icon('gym')} ${r.place==='gym'?'按已登记器械与常见健身房设备筛选':s.profile.equipment.length?esc(s.profile.equipment.map(e=>equipmentLabels[e]).join('、')):'默认无器械'}<button class="text-button" data-nav="body">设置器械</button></div>
  <button class="text-button" data-action="ai-settings">AI 数据发送设置</button>${ai.ready?`<button class="secondary full" data-action="generate" ${ai.busy?'disabled':''}>只用本地规则安排</button>`:''}</div></details></div></section>`;
}
// AI plans carry a prescription and a reason per item; rule-based plans do not.
function prescriptionHTML(i,s) {
  const a=i.activitySnapshot||getActivity(i.activityId);
  if(a.category==='strength')return `<p class="weight-reference">${esc(weightReference(a,s).text)}</p>${i.reason?`<details><summary>为什么推荐</summary><p class="small muted">${esc(i.reason)}</p></details>`:''}`;
  const x=i.prescription;if(!x&&!i.reason)return '';
  const dose=x?[x.sets&&(x.reps||x.seconds)?`${x.sets} 组 × ${x.reps?`${x.reps} 次`:`${x.seconds} 秒`}`:x.sets?`${x.sets} 组`:x.reps?`${x.reps} 次`:x.seconds?`${x.seconds} 秒`:'',x.perSide?'每侧':'',x.restSeconds?`休息 ${x.restSeconds} 秒`:'',x.load||''].filter(Boolean).join(' · '):'';
  return `${dose?`<p class="prescription">${esc(dose)}</p>`:''}${i.reason?`<p class="small muted">${esc(i.reason)}</p>`:''}`;
}
function planHTML(s,ai={}) {
  return s.draft.startedAt?runningHTML(s):preStartPlanHTML(s,ai);
}
// Before starting: the full list you can review, replace and adjust.
function preStartPlanHTML(s,ai={}) {
  const p=s.draft;
  return `<section class="card plan"><div class="plan-header"><div><span class="overline">为今天留的一点时间</span><h2>${planFocus(p.request)} · ${p.plannedMinutes+p.transitionMinutes} 分钟</h2><p>${places[p.request.place]} · ${p.items.length} 个活动 · ${p.transitionMinutes} 分钟转换与休息</p></div><button class="icon-button" data-action="discard" aria-label="撤下当前安排">${icon('close')}</button></div><div class="plan-reason">${icon('info')}<span>${esc(p.explanation)}${p.unallocatedMinutes>0?` 还有 ${p.unallocatedMinutes} 分钟留白，不为填满时间增加动作。`:''}${p.cautions?.length?p.cautions.map(c=>`<br>${esc(c)}`).join(''):''}</span></div>${p.knowledgeUsed?.length?`<div class="plan-knowledge">${icon('bookmark')}<span>参考了你的知识库：${p.knowledgeUsed.map(k=>`「${esc(k.title)}」${safeURL(k.url)?` <a class="text-button" href="${esc(safeURL(k.url))}" target="_blank" rel="noopener noreferrer">打开来源视频 ${icon('arrow')}</a>`:''}`).join('')}</span></div>`:p.usedCorpus===false?'<div class="plan-knowledge muted">这次没有参考你的知识库。</div>':''}${methodReportHTML(p)}${regionCoverageHTML(p)}<div class="plan-items">${p.items.map((i,index)=>{const a=getActivity(i.activityId);return `<div class="plan-item ${i.status}"><span class="order">${String(index+1).padStart(2,'0')}</span><div class="plan-item-main"><button class="item-title" data-detail="${a.id}">${a.name}</button><p>${goals[a.category]} · ${i.plannedMinutes} 分钟</p>${prescriptionHTML(i,s)}${activityVideoLinksHTML(s,a.id,a)}${getNote(s,a.id)?`<div class="mini-note">${icon('bookmark')}${esc(getNote(s,a.id))}</div>`:''}</div><div class="item-actions"><button class="icon-button" data-replace="${i.id}" aria-label="替换${a.name}">${icon('swap')}</button></div></div>`;}).join('')}</div><div class="plan-footer">${ai.ready&&(p.source==='ai'||p.source==='saved')?`<div class="ai-adjust"><input id="ai-adjust-text" maxlength="300" value="${esc(ai.adjustText||'')}" placeholder="想怎么调整？例如：换掉引体、再短一点、多练核心" aria-label="调整要求"><button class="secondary" data-action="ai-adjust" ${ai.busy?'disabled':''}>${ai.busy?'调整中…':'调整'}</button></div>`:''}<button class="primary full" data-action="start" ${ai.busy?'disabled':''}>${icon('play')} 开始这次活动</button><button class="secondary full save-template" data-action="save-template">${icon('bookmark')} ${p.templateId?'另存为新的收藏':'收藏这套训练'}</button></div></section>`;
}
// In progress: one focused card at a time; the rest folds into 「看全部」. Rest countdown lives in #rest (app.js).
function runningHTML(s) {
  const p=s.draft,total=p.items.length,done=p.items.filter(i=>i.status==='completed').length;
  const cursor=Math.max(0,Math.min(p.cursor??0,total)),cur=p.items[cursor];
  const no=n=>String(n+1).padStart(2,'0');
  const dots=p.items.map((i,idx)=>`<button class="run-dot ${i.status} ${idx===cursor?'current':''}" data-goto="${idx}" aria-label="第 ${idx+1} 项：${esc(getActivity(i.activityId).name)}"></button>`).join('');
  const top=`<div class="run-top"><div class="run-top-head"><span class="overline">正在进行</span><span class="run-elapsed" id="elapsed">${elapsedText(p.startedAt)}</span><button class="icon-button" data-action="discard" aria-label="结束并撤下安排">${icon('close')}</button></div><div class="run-progress"><div class="run-dots">${dots}</div><span class="run-count">${done} / ${total}</span></div></div>`;
  let card;
  if(cur){
    const a=getActivity(cur.activityId),x=cur.prescription;
    const target=x?[x.sets&&(x.reps||x.seconds)?`${x.sets} 组 × ${x.reps?`${x.reps} 次`:`${x.seconds} 秒`}`:x.sets?`${x.sets} 组`:x.reps?`${x.reps} 次`:x.seconds?`${x.seconds} 秒`:'',x.perSide?'每侧':'',x.load||''].filter(Boolean).join(' · '):'';
    card=`<div class="run-card"><div class="run-order">${no(cursor)} / ${String(total).padStart(2,'0')}</div><button class="item-title run-title" data-detail="${a.id}">${a.name}</button><p class="run-cat">${goals[a.category]}${cur.plannedMinutes?` · 计划 ${cur.plannedMinutes} 分钟`:''}${target?` · 目标 ${esc(target)}`:''}</p>${cur.reason?`<details class="run-why"><summary>为什么推荐</summary><p class="small muted">${esc(cur.reason)}</p></details>`:''}${isTimed(cur,a)?timedCard(cur,s):exerciseLogForm(cur,s)}<div class="run-actions"><button class="secondary" data-skip="${cur.id}">跳过这个动作</button><button class="primary" data-next>下一个 ${icon('arrow')}</button></div></div>`;
  } else {
    const skipped=p.items.filter(i=>i.status==='skipped').length;
    card=`<div class="run-card run-done"><span class="activity-icon strength">${icon('check')}</span><h2>这次都过了一遍</h2><p class="muted">${done} 项已记录${skipped?` · ${skipped} 项跳过`:''}。可以回上面某一项补记，或结束并写下整体感受。</p></div>`;
  }
  const allList=`<details class="run-all"><summary>看全部 ${total} 项 · ${done} 项已记录</summary><div class="run-all-list">${p.items.map((i,idx)=>{const a=getActivity(i.activityId),sets=recordedSetsHTML(i);return `<div class="run-all-row ${i.status} ${idx===cursor?'current':''}"><button class="run-goto" data-goto="${idx}"><span class="order">${i.status==='completed'?icon('check'):no(idx)}</span><span class="run-goto-name">${a.name}<small>${i.status==='skipped'?'已跳过':idx===cursor?'当前':goals[a.category]}</small></span></button><button class="text-button" data-skip="${i.id}">${i.status==='skipped'?'恢复':'跳过'}</button>${sets?`<div class="run-all-sets">${sets}</div>`:''}</div>`;}).join('')}</div></details>`;
  return `<section class="card plan running">${top}${p.pausedForDiscomfort?'<div class="notice error">已记录本次不舒服。请先结束这次活动，不继续增加负荷。</div>':''}${card}${allList}<div class="plan-footer"><button class="primary full" data-action="finish">结束并记下感受 ${icon('arrow')}</button></div></section>`;
}
export function libraryHTML(s,filters) {
  const q=filters.search.trim().toLowerCase();
  const rows=activities.filter(a=>(filters.personal==='mine'?a.personal:!a.archived)&&(filters.category==='all'||a.category===filters.category)&&(filters.system==='all'||a.system===filters.system)&&(filters.place==='all'||a.places.includes(filters.place))&&(filters.personal!=='notes'||Boolean(getNote(s,a.id)))&&(filters.personal!=='recent'||s.sessions.some(x=>x.items.some(i=>i.activityId===a.id&&i.status==='completed')))&&`${a.name}${a.aliases.join('')}${a.body.join('')}`.toLowerCase().includes(q));
  const pills=(key,options)=>options.map(([v,l])=>`<button class="pill ${filters[key]===v?'selected':''}" data-${key}="${v}">${l}</button>`).join('');
  return `${heading('YOUR MOVEMENT LIBRARY','找到适合你的动作','不同运动体系，共享一个动作库。你的心得，留在每个动作旁。',`<div class="heading-actions"><span class="count-label">${rows.length===activities.length?'':`${rows.length} / `}${activities.length} 个候选</span><button class="primary" data-action="add-activity">${icon('plus')} 添加我的动作</button></div>`)}<div class="filter-pills"><button class="pill ${filters.personal==='all'?'selected':''}" data-personal="all">全部</button><button class="pill ${filters.personal==='recent'?'selected':''}" data-personal="recent">最近练过</button><button class="pill ${filters.personal==='notes'?'selected':''}" data-personal="notes">有我的心得</button><button class="pill ${filters.personal==='mine'?'selected':''}" data-personal="mine">我的动作${activities.some(a=>a.personal)?` <small>${activities.filter(a=>a.personal&&!a.archived).length}</small>`:''}</button></div><div class="library-toolbar"><label class="search">${icon('search')}<input id="activity-search" placeholder="搜索动作、部位或英文名，如：髋、划船、plank" value="${esc(filters.search)}" aria-label="搜索动作"></label><select id="library-place" aria-label="筛选场地"><option value="all">全部场地</option>${Object.entries(places).map(([v,l])=>`<option value="${v}" ${filters.place===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="filter-pills" role="group" aria-label="筛选训练体系">${pills('system',[['all','全部体系'],...Object.entries(systems)])}</div><div class="filter-pills" role="group" aria-label="筛选能力">${pills('category',[['all','全部能力'],...Object.entries(goals).filter(([k])=>k!=='balanced')])}</div>${filters.personal==='mine'&&!rows.length?empty('还没有自己的动作','在知识库里对视频或文字点「提取动作」，或者点右上角「添加我的动作」。',`<button class="primary" data-action="add-activity">${icon('plus')} 添加我的动作</button>`):''}<div class="activity-grid">${rows.map(a=>`<button class="activity-card" data-detail="${a.id}">${a.personal&&a.source?.thumbnailId?`<img class="activity-card-image" data-local-image="${esc(a.source.thumbnailId)}" alt="${esc(a.name)}动作截图" loading="lazy">`:''}<div class="activity-card-top"><span class="activity-icon ${a.category}">${icon(a.category)}</span><span class="small muted">${a.personal?(a.archived?'我的动作 · 已归档':a.selectable?'我的动作 · 可自动安排':'我的动作 · 仅手动'):a.selectable===false?'仅供浏览':a.level?`第 ${a.level} 式 · ${tiers[a.tier]}`:esc(a.difficulty)}</span></div><h3>${a.name}</h3><p>${esc(a.description)}</p><div class="tags">${badge(systems[a.system])}${badge(goals[a.category])}${badge(a.equipment.length?a.equipment.map(e=>equipmentLabels[e]).join(' / '):'无器械')}</div><div class="activity-card-bottom"><span>${a.body.join(' · ')}</span>${getNote(s,a.id)?`<span class="note-indicator">${icon('bookmark')} 有心得</span>`:icon('chevron')}</div></button>`).join('')||(filters.personal==='mine'?'':empty('没有找到对应动作','试试其他部位或筛选条件。'))}</div><p class="prototype-note">候选库尚未完成专业审核；仅供浏览的动作不会进入自动安排，高级动作只在训练经历为「有规律训练」时安排。</p>`;
}
export function recordsHTML(s,ai={}) {
  return `${heading('EVERY SESSION COUNTS','留下身体的进步','练过什么、当时的感受，都在这里。',`<div class="heading-actions"><button class="primary" data-action="ai-log">${icon('plus')} 粘贴记录，AI 整理</button><button class="secondary" data-action="manual-log">手动补记</button><button class="secondary" data-action="import">恢复备份</button><button class="secondary" data-action="export">${icon('download')} 导出记录</button></div>`)}${s.sessions.length?`<div class="timeline">${[...s.sessions].reverse().map(s=>`<button class="session-card card" data-session="${s.id}"><div class="session-date"><strong>${dateText(s.endedAt,{day:'numeric'})}</strong><span>${dateText(s.endedAt,{month:'long'})}</span></div><div class="session-info"><h3>${s.planSnapshot?`${planFocus(s.planSnapshot.request)} · ${places[s.planSnapshot.request.place]}`:'补记的训练'}</h3><p>${s.items.filter(i=>i.status==='completed').map(i=>esc(i.activitySnapshot?.name || getActivity(i.activityId)?.name || i.customName || i.activityId)).join('、')}</p><span>${s.actualMinutes==null?'未填写实际时长':`${s.actualMinutes} 分钟`}${s.effort?` · 费力程度 ${s.effort}/10`:''}</span>${s.feedback?`<div class="session-quote">“${esc(s.feedback)}”</div>`:''}</div>${icon('chevron')}</button>`).join('')}</div>`:`<section class="card">${empty('第一条记录，等你开始','完成一次训练后，确认的动作和感受会自动出现在这里。',`<button class="primary" data-nav="today">安排今天的活动 ${icon('arrow')}</button>`)}</section>`}<section class="section"><div class="section-heading"><h2>身体随记</h2><button class="text-button" data-action="observation">${icon('plus')} 记一笔</button></div>${s.observations.length?`<div class="observation-list">${[...s.observations].reverse().map(o=>`<article class="card observation"><span class="overline">${dateText(o.createdAt)}</span><p>${esc(o.text)}</p><span class="small muted">个人感受 · 尚未进行专业评估</span></article>`).join('')}</div>`:'<p class="muted">暂时没有身体随记。睡眠、疲劳或不适，都可以记录在这里。</p>'}</section>`;
}
// 主题总结：AI 按主题归纳整个知识库；新内容攒够了在这里提示整理。
function topicSectionHTML(s) {
  const d=pendingDigest(s),cards=s.topicCards||[];
  if(!d.canDigest&&!cards.length)return '';
  const titleOf=id=>s.knowledge.find(k=>k.id===id)?.title;
  const card=t=>`<article class="card method-card"><div class="section-heading">${badge('主题总结')}<span class="small muted">#${esc(t.topic)} · ${dateText(t.updatedAt||t.createdAt)} · ${t.sourceKnowledgeIds.length} 条来源</span></div><h3>${esc(t.title)}</h3>${t.summary?`<p>${esc(t.summary)}</p>`:''}<ol class="method-principles">${t.principles.map(p=>`<li>${esc(p.text)}<details><summary>${p.sources.length} 条来源依据</summary>${p.sources.map(x=>`<p class="small muted">${esc(titleOf(x.knowledgeId)||'来源已删除')}：「${esc(x.quote)}」</p>`).join('')}</details></li>`).join('')}</ol><footer><label class="checkbox-line"><input type="checkbox" data-topic-planning="${esc(t.id)}" ${t.allowedInPlanning!==false?'checked':''}>用于安排参考</label><button class="text-button" data-delete-topic="${esc(t.id)}">删除</button></footer></article>`;
  return `<section class="section method-section"><div class="section-heading"><h2>主题总结</h2><span>AI 按主题归纳你的整个知识库，每条都附出处</span></div>${d.shouldPrompt?`<div class="notice">有 ${d.fresh} 条知识${s.digestedAt?'在上次整理后新加入，':''}还没有归纳。<button class="text-button orange" data-action="digest">现在整理 ${icon('arrow')}</button></div>`:''}${d.canDigest?`<button class="secondary" data-action="digest">${cards.length?'重新整理知识库':'整理知识库'}${s.digestedAt?`<span class="small muted">（上次 ${dateText(s.digestedAt)}）</span>`:''}</button>`:`<p class="muted">再收 ${3-d.total} 条知识就可以整理。</p>`}${cards.length?`<div class="knowledge-grid">${[...cards].reverse().map(card).join('')}</div>`:''}</section>`;
}
// 创作者方法卡：把同一位创作者的多张已确认知识卡，归纳成一张可回顾的方法卡。
// 仅在已有可归组的创作者或已保存方法卡时显示，避免空占版面。
function methodSectionHTML(s) {
  const groups=creatorGroups(s),profiles=s.creatorProfiles||[];
  if(!groups.length&&!profiles.length)return '';
  const groupRow=g=>`<div class="method-creator"><div><strong>${esc(g.creatorName)}</strong><span class="small muted">${g.cardCount} 张已确认知识卡${g.methodCardId?' · 已有方法卡':''}</span></div>${g.canSynthesize?`<button class="text-button orange" data-synthesize-method="${esc(g.creatorKey)}">${g.methodCardId?'重新整理':'整理方法卡'} ${icon('arrow')}</button>`:`<span class="small muted">再收 1 张同一创作者的卡即可整理</span>`}</div>`;
  const titleOf=id=>s.knowledge.find(k=>k.id===id)?.title;
  const cardRow=p=>`<article class="card method-card"><div class="section-heading">${badge('方法卡')}<span class="small muted">${esc(p.creatorName)} · ${dateText(p.updatedAt||p.createdAt)}</span></div><h3>${esc(p.title)}</h3>${p.summary?`<p>${esc(p.summary)}</p>`:''}<ol class="method-principles">${(p.principles||[]).map(pr=>`<li>${esc(pr.text)}${pr.sources?.length?`<details><summary>${pr.sources.length} 条来源依据</summary>${pr.sources.map(src=>`<p class="small muted">${esc(titleOf(src.knowledgeId)||'来源知识卡')}：「${esc(src.quote)}」</p>`).join('')}</details>`:''}</li>`).join('')}</ol>${p.activityIds?.length?`<div class="tags">${p.activityIds.map(id=>`<button class="badge" data-detail="${esc(id)}">${esc(getActivity(id)?.name||id)}</button>`).join('')}</div>`:''}${p.unknowns?.length?`<p class="small muted">还缺：${p.unknowns.map(esc).join('；')}</p>`:''}<footer><label class="checkbox-line"><input type="checkbox" data-method-planning="${esc(p.id)}" ${p.allowedInPlanning?'checked':''}>用于安排参考（开启「参考我的知识库」时）</label><button class="text-button" data-delete-method="${esc(p.id)}">删除</button></footer></article>`;
  return `<section class="section method-section"><div class="section-heading"><h2>创作者方法卡</h2><span>把同一位创作者的多张知识卡，归纳成一张方法卡</span></div>${groups.map(groupRow).join('')||'<p class="muted">还没有能识别创作者的已确认知识卡。</p>'}${profiles.length?`<div class="knowledge-grid">${profiles.map(cardRow).join('')}</div>`:''}<p class="prototype-note">方法卡只复述你已确认知识卡里的观点，逐条附来源；观点未经专业审核，即使允许参考也不会绕过当天的安全、器械和时间限制。</p></section>`;
}
export function knowledgeHTML(s,filter,topic='',kind='',contentType='') {
  const kindOf=k=>entryKind(k,(s.captures||[]).find(c=>c.knowledgeId===k.id));
  const captureFor=k=>(s.captures||[]).find(c=>c.knowledgeId===k.id);
  const typeOf=k=>k.contentType||captureFor(k)?.cardDraft?.contentType||'';
  const rows=s.knowledge.filter(k=>(filter==='all'||k.status===filter)&&(!topic||normalizeTopics(k.topics).includes(topic))&&(!kind||kindOf(k)===kind)&&(!contentType||typeOf(k)===contentType));
  const time=ms=>ms==null?'':`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
  const evidenceLabel=x=>x.evidenceKind==='ai_search'?'AI 搜索来源（待核对）':x.evidenceKind==='image_description'?`图集第 ${(x.imageIndex??0)+1} 张 · AI 图像描述（待核对）`:x.evidenceKind==='omni_audio_video_summary'?'Omni 音画理解（待核对）':x.evidenceSource==='workflow_model'?'AI 画面描述（待核对）':x.evidenceKind==='user_summary'?'你自己写的视频总结':x.evidenceKind==='asr_transcript'?'视频语音':x.evidenceKind==='frame_ocr'?'画面字幕':x.evidenceKind==='keyframe_description'?'画面解析':'原文';
  const cards=rows.map(k=>{
    const c=captureFor(k),claims=Array.isArray(k.claims)?k.claims:[];
    const hasText=Boolean(c?.shareText||c?.manualSummary||c?.transcript?.text||(Array.isArray(c?.videoEvidence)&&c.videoEvidence.length)||(Array.isArray(c?.imageEvidence)&&c.imageEvidence.length));
    const autoPossible=['douyin','xiaohongshu','bilibili'].includes(c?.platform)&&Boolean(c?.rawUrl);
    const status=c?.manualSummary?'你的手动总结 · 原视频已保留':c?.videoAnalysis?.provider==='bailian_omni_video_url'?'长视频 Omni 音画摘要 · 无逐字稿/截图，待核对':c?.videoAnalysis?.provider==='bailian_video_url'?'长视频 AI 画面摘要 · 无截图，待核对':c?.ingestStatus==='queued'?'云端正在读取视频内容':c?.cardDraft?'知识卡草稿待核对':c?.ingestStatus==='transcribed'?(c?.imageAnalysis?'抖音图文已分析 · 待核对':c?.videoAnalysis?'视频已解析':'视频已转成文字'):c?.ingestStatus==='failed'?'自动整理未完成':hasText?'有来源文字':'待补充内容';
    const actionSegments=Array.isArray(c?.actionSegments)?c.actionSegments:[];
    const segmentTitle=typeOf(k)==='follow_along'?'跟练流程':'视频动作片段';
    const segmentsHTML=actionSegments.length?`<details class="video-action-segments"><summary>${segmentTitle}（${actionSegments.length}）</summary>${actionSegments.map(seg=>`<section class="video-action-segment"><div class="video-action-time">${time(seg.startMs)}–${time(seg.endMs)} · ${esc(seg.name||'待确认动作')}</div>${seg.evidence.some(e=>e.evidenceSource==='workflow_model')?'<span class="badge warm">AI 画面描述 · 待核对</span>':''}${seg.thumbnail?`<img class="video-action-image" data-frame-capture="${esc(c.id)}" data-frame-segment="${esc(seg.id)}" alt="${esc(seg.name||'动作')}代表画面" loading="lazy">`:'<p class="small muted">这段暂时没有可用截图。</p>'}<p>${esc(seg.description||'')}</p>${seg.instruction?`<p class="small">口播 / 字幕：${esc(seg.instruction)}</p>`:''}${seg.uncertainty?`<p class="small muted">待确认：${esc(seg.uncertainty)}</p>`:''}<p class="small muted">依据：${seg.evidence.map(e=>`「${esc(e.quote)}」`).join('；')}</p><button class="text-button orange" data-extract-action-segment="${esc(k.id)}" data-segment-id="${esc(seg.id)}">核对并提取这个动作 ${icon('arrow')}</button></section>`).join('')}</details>`:'';
    const omniEvidence=Array.isArray(c?.videoEvidence)&&c.videoAnalysis?.provider==='bailian_omni_video_url'?c.videoEvidence.filter(x=>x.kind==='omni_audio_video_summary'):[];
    const omniSegmentsHTML=omniEvidence.length?`<details class="video-action-segments omni-action-segments"><summary>Omni 时间分段与动作提取（${omniEvidence.length} 段）</summary><p class="small muted">这些时间段是 AI 对整段声画的摘要，不是逐字稿或截图。可以按段提取动作草稿；保存前请打开原视频核对，动作默认仅手动使用。</p>${omniEvidence.map(item=>`<section class="video-action-segment"><div class="video-action-time">${time(item.startMs)}–${time(item.endMs)}</div><span class="badge warm">Omni 音画摘要 · 待核对</span><p>${esc(item.text)}</p><button class="text-button orange" data-extract-omni-segment="${esc(k.id)}" data-evidence-id="${esc(item.id)}">核对并从这一段提取动作 ${icon('arrow')}</button></section>`).join('')}</details>`:'';
    const imageEvidence=Array.isArray(c?.imageEvidence)?c.imageEvidence:[];
    const imageEvidenceHTML=imageEvidence.length?`<details class="douyin-image-evidence"><summary>抖音图文识别（${imageEvidence.length} 张）</summary><p class="small muted">下面是 AI 对每张图的观察，不是作者原话；预览临时保存两天，过期后可打开原图文核对。</p>${imageEvidence.map(image=>`<figure class="douyin-image-item">${image.thumbnail?`<img class="douyin-image-preview" data-capture-image="${esc(c.id)}" data-image-index="${image.imageIndex}" alt="第 ${image.imageIndex+1} 张图文预览" loading="lazy">`:'<p class="small muted">这张图没有可用的临时预览。</p>'}<figcaption><strong>第 ${image.imageIndex+1} 张 · AI 观察（${esc(image.confidence||'low')}）</strong><p>${esc(image.observation||image.text)}</p>${image.visibleText?`<p class="small muted">图片文字（AI 识别）：${esc(image.visibleText)}</p>`:''}</figcaption></figure>`).join('')}</details>`:'';
    let actions=c?.ingestStatus==='queued'?'<span class="small muted">后台处理中；离开页面后可回来查看</span>'
      :c?.ingestErrorCode==='too_long'?`<span class="small muted">视频超过 30 分钟，不会自动读取或上传；你可以自己写总结并保留原链接。</span><button class="text-button" data-copy-video-url="${esc(c.id)}">复制视频链接</button><button class="text-button orange" data-manual-video-summary="${esc(c.id)}">${c.manualSummary?'编辑我的总结':'自己整理这条视频'} ${icon('edit')}</button>`
      :c?.cardDraft?`<button class="text-button orange" data-review-ingest="${esc(c.id)}">核对知识卡 ${icon('arrow')}</button>`
      :c?.ingestStatus==='failed'&&autoPossible?`<button class="text-button orange" data-auto-ingest="${esc(c.id)}" data-force-ingest="true">重试自动整理</button>${hasText?`<button class="text-button" data-analyze-capture="${esc(c.id)}">用已有文字整理</button>`:''}`
      :c?.ingestStatus==='transcribed'?`<button class="text-button orange" data-auto-ingest="${esc(c.id)}" data-force-ingest="true">${c?.imageAnalysis?'重新分析图文':'重新解析视频'} ${icon('arrow')}</button>${hasText?`<button class="text-button" data-analyze-capture="${esc(c.id)}">${c?.imageAnalysis?'用已有图像观察整理':'只用现有文字整理'}</button>`:''}`
      :autoPossible?`<button class="text-button orange" data-auto-ingest="${esc(c.id)}">自动转成知识卡 ${icon('arrow')}</button>${hasText?`<button class="text-button" data-analyze-capture="${esc(c.id)}">用已有文字整理</button>`:''}`
      :hasText?`<button class="text-button orange" data-analyze-capture="${esc(c.id)}">AI 整理 ${icon('arrow')}</button>`
      :c?`<button class="text-button orange" data-edit-capture="${esc(c.id)}">补充内容 ${icon('edit')}</button>`
      :k.status==='inbox'?`<button class="text-button orange" data-save-knowledge="${esc(k.id)}">收进个人库 ${icon('check')}</button>`:'';
    const planDetail=k.status==='saved'&&k.planPoints?.length?`<details class="plan-outline"><summary>来源里的训练安排（${k.planPoints.length}）</summary>${k.planPoints.map(p=>`<div class="plan-outline-row"><strong>${esc(PLAN_POINT_KINDS[p.kind]||'方案内容')}</strong><span>${esc(p.text)}</span><small class="muted">${p.startMs!=null?`${time(p.startMs)} · `:''}${p.evidenceSource==='workflow_model'?'AI 依据（待核对）':'原文'}：「${esc(p.evidenceQuote)}」</small></div>`).join('')}</details>`:'';
    actions=planDetail+imageEvidenceHTML+segmentsHTML+omniSegmentsHTML+(CONTENT_TYPES[typeOf(k)]?badge(CONTENT_TYPES[typeOf(k)]):'')+actions;
    const sourceUrl=c?.rawUrl||k.url;
    return `<article class="card knowledge-card"><div class="section-heading">${badge(k.status==='inbox'?'待整理':'个人知识卡',k.status==='inbox'?'warm':'')}<button class="icon-button" data-edit-knowledge="${esc(k.id)}" aria-label="编辑${esc(k.title)}">${icon('edit')}</button></div><h3>${esc(k.title)}</h3><p>${esc(k.text)}</p>${c?.ingestStatus==='failed'?`<p class="small muted">${esc(c.ingestError||'链接已保留，可稍后重试。')}</p>${c.lastIngestAttempt?.id?`<p class="small muted">任务 ${esc(c.lastIngestAttempt.id.slice(0,8))} · ${esc(c.lastIngestAttempt.pipelineVersion||'')}</p>`:''}`:''}${c?.ingestWarning?`<p class="small muted">${esc(c.ingestWarning)}</p>`:''}${claims.length?`<details><summary>查看 ${claims.length} 条来源依据</summary>${claims.map(x=>`<p>${esc(x.text)}<br><span class="small muted">${evidenceLabel(x)}${x.startMs!=null?` ${time(x.startMs)}`:''}：${x.evidenceKind==='ai_search'&&Array.isArray(x.sources)?x.sources.map(src=>safeURL(src.url)?`<a href="${esc(safeURL(src.url))}" target="_blank" rel="noopener noreferrer">${esc(src.title)}${src.site?` · ${esc(src.site)}`:''}</a>`:'').join('；'):`「${esc(x.evidenceQuote)}」`}</span></p>`).join('')}</details>`:''}${c?.transcript?.text?`<details><summary>${c.transcript.model==='platform-subtitle'?'查看平台字幕':c.ingestStatus==='failed'?'查看上次视频逐字稿':'查看视频逐字稿'}</summary><p class="small muted">自动语音识别可能有误，请结合原视频核对。</p><p>${esc(c.transcript.text)}</p></details>`:''}<div class="tags">${k.activityIds.map(id=>`<button class="badge" data-detail="${esc(id)}">${esc(getActivity(id)?.name||id)}</button>`).join('')}</div>${k.status==='saved'?(()=>{const kind=entryKind(k,c),trust=entryTrust(k,kind);return `<div class="tags">${badge(SOURCE_KINDS[kind])}${lowTrust(trust)?badge(TRUST_LEVELS[trust],'warm'):''}${normalizeTopics(k.topics).map(t=>`<button class="badge topic" data-knowledge-topic="${esc(t)}"># ${esc(t)}</button>`).join('')}</div>`;})():''}<div class="knowledge-source">${icon('bookmark')} ${esc(k.sourceTitle||'我的收藏')} · ${status}</div><footer>${safeURL(sourceUrl)?`<a class="text-button" href="${esc(safeURL(sourceUrl))}" target="_blank" rel="noopener noreferrer">${kindOf(k)==='video'?'打开原视频':kindOf(k)==='image_post'?'打开原图文':'打开来源'} ${icon('arrow')}</a>`:'<span class="small muted">保留原始思考</span>'}${k.useInPlanning?'<span class="badge">允许推荐参考</span>':''}${actions}${k.status==='saved'&&hasText?`<button class="text-button" data-extract-activities="${esc(k.id)}">提取动作</button>`:''}<button class="text-button" data-delete-knowledge="${esc(k.id)}">删除</button></footer></article>`;
  }).join('');
  return `${heading('COLLECT · THINK · PRACTICE','让好想法留下来','把收藏变成理解，再变成对自己有用的练习。',`<div class="heading-actions"><button class="secondary" data-action="knowledge-ask">问我的知识库</button><button class="primary" data-action="capture">${icon('plus')} 收藏一条分享</button></div>`)}<div class="capture-banner">${icon('link')}<div><h3>刷到一个想试的动作？</h3><p>直接粘贴抖音、小红书或 B 站分享文案，循动会提取链接并尝试解析口播、画面和字幕。</p></div><button class="icon-button" data-action="capture" aria-label="收藏一条分享">${icon('plus')}</button></div><div class="source-actions"><button class="secondary" data-action="book">${icon('bookmark')} 书摘 / 读书笔记</button><button class="secondary" data-action="knowledge-search">${icon('search')} AI 联网搜索</button><button class="secondary" data-action="add-knowledge">${icon('edit')} 写下自己的想法</button></div><div class="filter-pills">${[['all','全部内容'],['inbox','待整理'],['saved','已收进个人库']].map(([v,l])=>`<button class="pill ${v===filter?'selected':''}" data-knowledge-filter="${v}">${l}</button>`).join('')}</div><div class="filter-pills kind-pills" role="group" aria-label="按来源筛选">${[['','全部来源'],...Object.entries(SOURCE_KINDS)].map(([v,l])=>`<button class="pill ${v===kind?'selected':''}" data-knowledge-kind="${v}">${l}</button>`).join('')}</div>${(()=>{const topics=corpusTopics(s);return topics.length?`<div class="filter-pills topic-pills" role="group" aria-label="按主题筛选">${topic?`<button class="pill selected" data-knowledge-topic="">#${esc(topic)} ✕</button>`:''}${topics.filter(t=>t.topic!==topic).slice(0,20).map(t=>`<button class="pill" data-knowledge-topic="${esc(t.topic)}">#${esc(t.topic)} <small>${t.count}</small></button>`).join('')}</div>`:'';})()}${(()=>{const u=storageUsage(s);return u.level==='ok'?'':`<div class="notice ${u.level==='full'?'error':''}">本机存储已用 ${u.text}。${u.level==='full'?'快满了，请先导出备份；之后会迁到容量更大的存储。':'书只存摘录和笔记，不存全文。'}</div>`;})()}<div class="knowledge-grid">${cards||empty('这里还没有内容','收藏一条分享，或换一个分类。')}</div>${topicSectionHTML(s)}${methodSectionHTML(s)}<p class="prototype-note">知识库是长期保存的个人语料，不设数量上限；本机存储已用 ${storageUsage(s).text}。视频接入上限 30 分钟；15 分钟内支持解析器证据和关键帧，15～30 分钟通过阿里云 FC 使用 Omni AI 音画摘要（口播非逐字稿、无解析器截图，保存前请核对）；Cloudflare 对超过 15 分钟的视频会提示切换线路。小红书图文只整理正文。需要在「我的身体 → 自动视频整理」配置你自己的云端服务；失败也会保留原始链接。</p>`;
}
export function bodyHTML(s) {
  const p=s.profile;
  return `${heading('GET TO KNOW YOURSELF','认识身体，慢慢来','从你知道的情况开始，不必一次填写完整。')}<div class="profile-grid"><form id="profile-form" class="card profile-form"><h2>我的基本设置</h2><label>怎么称呼你<input name="name" value="${esc(p.name)}" maxlength="30" placeholder="你的称呼（可选）"></label><div class="field-row"><label>当前训练经历<select name="experience"><option value="beginner" ${p.experience==='beginner'?'selected':''}>刚开始 / 重新开始</option><option value="regular" ${p.experience==='regular'?'selected':''}>有规律训练经历</option></select></label><label>默认训练重点<select name="focus">${Object.entries(goals).map(([v,l])=>`<option value="${v}" ${p.focus===v?'selected':''}>${l}</option>`).join('')}</select></label></div><label class="check-pill wide"><input type="checkbox" name="skipWarmup" ${p.skipWarmup?'checked':''}><span>不习惯热身，直接开练（自动安排时跳过热身与放松）</span></label><div class="field-row"><label>年龄段（可选）<select name="ageRange">${[['','暂不填写'],['under18','未满18岁'],['18-39','18–39岁'],['40-64','40–64岁'],['65+','65岁及以上']].map(([v,l])=>`<option value="${v}" ${p.ageRange===v?'selected':''}>${l}</option>`).join('')}</select></label><label>常参与的运动<input name="preferredSports" maxlength="200" value="${esc(p.preferredSports||'')}" placeholder="例如：羽毛球、跑步"></label></div><div class="field-row"><label>平均睡眠（小时，可选）<input name="sleepHours" type="number" min="0" max="24" step="0.5" value="${p.sleepHours??''}"></label><label>日均久坐（小时，可选）<input name="sittingHours" type="number" min="0" max="24" step="0.5" value="${p.sittingHours??''}"></label></div><label>最近想改善什么<textarea name="goalText" placeholder="例如：工作间隙多活动；提高羽毛球步伐协调性" maxlength="2000">${esc(p.goalText)}</textarea></label><fieldset><legend>我可以使用的器械</legend><div class="equipment-checks">${Object.entries(equipmentLabels).map(([v,l])=>`<label class="check-pill"><input type="checkbox" name="equipment" value="${v}" ${p.equipment.includes(v)?'checked':''}><span>${l}</span></label>`).join('')}</div></fieldset><label>需要留意的身体情况<textarea name="bodyNotes" placeholder="可选：既往受伤、近期不适、专业人员给出的限制……" maxlength="4000">${esc(p.bodyNotes)}</textarea></label><p class="helper left">此处文字仅作为档案保存。程序不会把自然语言病史当作已完成医学评估；填写限制后，本地规则与 AI 都会暂停自动安排，供进一步评估。</p><button class="primary" type="submit">保存我的设置 ${icon('check')}</button></form><aside>${capacityHTML(s)}${privacyHTML(s)}</aside></div>`;
}
