import { activities, goals, places, equipmentLabels, bodyRegions, regionLabel, systems, tiers } from './catalog.js';
import { capacityHTML,privacyHTML,recordedSetsHTML,exerciseLogForm,timedCard } from './experience.js';
import { weightReference,isTimed } from './training.js';
import { weekSummary, safeURL } from './domain.js';
import { esc, icon, badge, dateText, empty, elapsedText } from './ui.js';
export const routes = { today:'今天', records:'训练记录', library:'动作库', knowledge:'知识库', body:'我的身体' };
const getActivity = id => activities.find(a => a.id === id);
const getNote = (s,id) => s.notes.find(n => n.activityId === id)?.text;
const heading = (eyebrow,title,sub,aside='') => `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}<span class="orange">。</span></h1><p>${sub}</p></div>${aside}</div>`;
export function shell(page,state,content,error=false) {
  const nav=(mobile=false)=>Object.entries(routes).map(([id,label])=>`<button class="nav-item ${page===id?'active':''}" data-nav="${id}" ${page===id?'aria-current="page"':''}>${icon(id)}<span>${mobile&&id==='records'?'记录':mobile&&id==='body'?'身体':label}</span></button>`).join('');
  return `<aside class="sidebar"><a class="brand" href="#today"><img src="/icon.svg" alt=""/><span>循动<small>MOVE WITH YOUR LIFE</small></span></a><div class="nav-caption">我的运动空间</div><nav aria-label="主要导航">${nav()}</nav><div class="sidebar-bottom"><div class="local-indicator">${icon('bookmark')}<div>你的私人练习簿<small>仅保存在当前浏览器</small></div></div><button class="text-button" data-action="export">${icon('download')} 导出我的记录</button><div class="version">界面原型 · v0.1</div></div></aside>
  <main><header class="topbar"><span class="breadcrumb">我的运动空间 <span>/</span> ${routes[page]}</span><span class="topdate">${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span><button class="avatar" data-nav="body" aria-label="打开我的身体档案">${esc(state.profile.name.slice(0,1)||'我')}</button></header><div class="content">${error?'<div class="notice error">本地记录读取异常。已暂停保存，原始数据未被覆盖。</div>':''}${content}</div></main><nav class="bottom-nav" aria-label="手机导航">${nav(true)}</nav>`;
}
export function todayHTML(s,r,ai={}) {
  const summary=weekSummary(s.sessions);
  return `${heading('A LITTLE MOVEMENT, EVERY DAY','今天，动一点','从现在有的时间开始，找到适合今天的节奏。',`<span class="heading-icon">${icon('sun')}</span>`)}<div class="today-grid"><div class="primary-column">${s.draft?planHTML(s,ai):plannerHTML(s,r,ai)}
  <section class="section"><div class="section-heading"><h2>从生活里的小空隙开始</h2><span>无需等到有空的一天</span></div><div class="quick-grid">
  <button class="quick-card peach" data-preset="office"><span class="quick-icon">${icon('office')}</span><strong>工作间隙</strong><span>离开椅子，活动一下</span><footer>5 分钟 ${icon('arrow')}</footer></button>
  <button class="quick-card lavender" data-preset="mobility"><span class="quick-icon">${icon('mobility')}</span><strong>舒展身体</strong><span>留一点时间给活动度</span><footer>10 分钟 ${icon('arrow')}</footer></button>
  <button class="quick-card blue" data-preset="recovery"><span class="quick-icon">${icon('recovery')}</span><strong>慢下来</strong><span>呼吸、离屏、轻松走动</span><footer>5 分钟 ${icon('arrow')}</footer></button></div></section></div>
  <aside class="right-column"><section class="card weekly"><div class="section-heading"><h2>最近 7 天</h2>${icon('today')}</div><div class="stats"><div><strong>${summary.sessions}</strong><span>次已记录训练</span></div><div><strong>${summary.minutes}<small> min</small></strong><span>已填写的实际时长</span></div></div><div class="week-strip">${Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const did=s.sessions.some(s=>new Date(s.endedAt).toDateString()===d.toDateString());return `<div class="day ${did?'did':''} ${i===6?'current':''}"><span>${['日','一','二','三','四','五','六'][d.getDay()]}</span><b>${did?icon('check'):d.getDate()}</b></div>`;}).join('')}</div><p class="muted small">${summary.unknown?`${summary.unknown} 次训练未填写时长。`:'只统计你确认完成的训练。'}${summary.sessions?'':'第一次记录，从今天开始。'}</p><button class="text-button" data-nav="records">查看训练记录 ${icon('arrow')}</button></section>
  <section class="card body-prompt"><span class="overline">先听听身体的声音</span><h2>今天感觉怎么样？</h2><p>睡眠、疲劳和不舒服的地方，都可以慢慢记下来。</p><button class="secondary full" data-action="observation">${icon('plus')} 记一下身体状态</button></section>${s.notes.length?`<section class="notebook"><span class="overline">来自你的练习簿</span><p>「${esc(s.notes.at(-1).text)}」</p><button class="text-button" data-detail="${s.notes.at(-1).activityId}">查看我的心得 ${icon('arrow')}</button></section>`:`<section class="notebook"><span class="overline">让下次练习更顺手</span><p>给一个动作写下自己的发力提示和感受。</p><button class="text-button" data-nav="library">打开动作库 ${icon('arrow')}</button></section>`}</aside></div><p class="prototype-note">记录默认留在本机；AI 仅在你启用并主动请求时发送数据。尚未连接健康设备。</p>`;
}
function planFocus(request) {
  return request.focus==='strength' && request.targetRegions?.length ? `力量 · ${regionLabel(request.targetRegions)}` : goals[request.focus];
}
function strengthSelector(r) {
  const selected=r.targetRegions||[];
  const choice=([id,region])=>`<button type="button" class="region-choice ${selected.includes(id)?'selected':''}" data-region="${id}" aria-pressed="${selected.includes(id)}"><span>${region.label}</span>${selected.includes(id)?icon('check'):''}</button>`;
  return `<fieldset class="strength-selector"><legend>今天想练哪些部位？<span>可多选</span></legend><button type="button" class="region-all ${selected.length?'':'selected'}" data-region="all" aria-pressed="${!selected.length}">${icon('today')} 全身均衡，帮我安排${!selected.length?icon('check'):''}</button><div class="region-grid" role="group" aria-label="常用训练部位">${Object.entries(bodyRegions).filter(([,v])=>v.common).map(choice).join('')}</div><details id="region-more" ${selected.some(id=>!bodyRegions[id]?.common)?'open':''}><summary>更多部位<span>前臂、足踝、颈部</span></summary><div class="region-extra" role="group" aria-label="更多训练部位">${Object.entries(bodyRegions).filter(([,v])=>!v.common).map(choice).join('')}</div></details><p class="region-hint">${selected.length?selected.map(id=>`${bodyRegions[id].label}：${bodyRegions[id].detail}`).join('；'):'不确定就保留全身均衡；有重点时，先选 1～2 项即可。'}</p>${selected.includes('neck')?'<p class="region-caution">颈部目前没有可自动推荐的力量动作，系统会保留这一内容缺口。</p>':''}</fieldset>`;
}
function regionCoverageHTML(plan) {
  if(!plan.regionCoverage?.length)return '';
  const included=plan.regionCoverage.filter(x=>x.status==='included').map(x=>x.id);
  const missing=plan.regionCoverage.filter(x=>x.status==='unavailable').map(x=>x.id);
  const limited=plan.regionCoverage.filter(x=>x.status==='time_limited').map(x=>x.id);
  return `<div class="region-coverage"><p>本次主要训练：${regionLabel(included)||'暂无'}</p>${missing.length?`<p class="muted">尚未匹配：${regionLabel(missing)}（场地、器械或动作库限制）</p>`:''}${limited.length?`<p class="muted">本次时间内未安排：${regionLabel(limited)}</p>`:''}<span>这是计划覆盖，不代表已经完成训练。</span></div>`;
}

function plannerHTML(s,r,ai={}) {
  return `<section class="card planner"><div class="planner-top"><div><span class="overline">留给自己的时间</span><h2>现在，想动多久？</h2></div><div class="duration-display"><strong>${r.minutes}</strong><span>分钟</span></div></div><div class="duration-options" role="group" aria-label="运动时间">${[5,10,20,30,45,60].map(n=>`<button data-minutes="${n}" class="${r.minutes===n?'selected':''}" aria-pressed="${r.minutes===n}">${n}<small>分</small></button>`).join('')}</div>
  <div class="planner-fields"><div class="place-options" role="group" aria-label="训练地点">${Object.entries(places).map(([id,label])=>`<button data-place="${id}" class="${r.place===id?'selected':''}" aria-pressed="${r.place===id}">${icon(id)}${label}</button>`).join('')}</div>
  ${ai.ready?`<label class="ai-box">说说今天想怎么练（可选）<textarea id="ai-text" maxlength="1000" rows="2" placeholder="例如：想练上肢，今天只有哑铃">${esc(ai.text||'')}</textarea></label>`:''}
  <button class="primary full" data-action="generate-smart" ${ai.busy?'disabled':''}>${ai.busy?'正在安排…':`给我安排 ${icon('arrow')}`}</button>
  <p class="helper">${ai.ready&&s.settings?.aiConsent?'使用 AI 辅助；必要时可切换本地规则。':'当前使用本地规则，不发送身体记录。'}</p>
  <details id="planning-options" ${ai.optionsOpen?'open':''}><summary>调整重点、部位与状态 <span>${goals[r.focus]}</span></summary><div class="advanced-options"><div class="field-row"><label>今天想侧重<select id="focus">${Object.entries(goals).map(([id,l])=>`<option value="${id}" ${r.focus===id?'selected':''}>${l}</option>`).join('')}</select></label><label>当前状态<select id="readiness"><option value="normal" ${r.readiness==='normal'?'selected':''}>状态还不错</option><option value="tired" ${r.readiness==='tired'?'selected':''}>有点疲惫</option><option value="discomfort" ${r.readiness==='discomfort'?'selected':''}>身体有不舒服</option></select></label></div>${r.focus==='strength'?strengthSelector(r):''}<div class="equipment-line">${icon('gym')} ${r.place==='gym'?'按已登记器械与常见健身房设备筛选':s.profile.equipment.length?esc(s.profile.equipment.map(e=>equipmentLabels[e]).join('、')):'默认无器械'}<button class="text-button" data-nav="body">设置器械</button></div>
  <button class="text-button" data-action="ai-settings">AI 数据发送设置</button>${ai.ready?`<button class="secondary full" data-action="generate" ${ai.busy?'disabled':''}>只用本地规则安排</button>`:''}</div></details></div></section>`;
}
// AI plans carry a prescription and a reason per item; rule-based plans do not.
function prescriptionHTML(i,s) {
  const a=i.activitySnapshot||getActivity(i.activityId);
  if(a.category==='strength')return `<p class="weight-reference">${esc(weightReference(a,s).text)}</p>${i.reason?`<details><summary>为什么推荐</summary><p class="small muted">${esc(i.reason)}</p></details>`:''}`;
  const x=i.prescription;if(!x&&!i.reason)return '';
  const dose=x?[x.sets&&(x.reps||x.seconds)?`${x.sets} 组 × ${x.reps?`${x.reps} 次`:`${x.seconds} 秒`}`:x.sets?`${x.sets} 组`:x.reps?`${x.reps} 次`:x.seconds?`${x.seconds} 秒`:'',x.perSide?'每侧':'',x.restSeconds?`休息 ${x.restSeconds} 秒`:'',x.load||''].filter(Boolean).join(' · '):'';
  return `${dose?`<p class="prescription">${esc(dose)}</p>`:''}${i.reason?`<p class="small muted">${esc(i.reason)}</p>`:''}`;
}
function planHTML(s,ai={}) {
  return s.draft.startedAt?runningHTML(s):preStartPlanHTML(s,ai);
}
// Before starting: the full list you can review, replace and adjust.
function preStartPlanHTML(s,ai={}) {
  const p=s.draft;
  return `<section class="card plan"><div class="plan-header"><div><span class="overline">为今天留的一点时间</span><h2>${planFocus(p.request)} · ${p.plannedMinutes+p.transitionMinutes} 分钟</h2><p>${places[p.request.place]} · ${p.items.length} 个活动 · ${p.transitionMinutes} 分钟转换与休息</p></div><button class="icon-button" data-action="discard" aria-label="撤下当前安排">${icon('close')}</button></div><div class="plan-reason">${icon('info')}<span>${esc(p.explanation)}${p.unallocatedMinutes>0?` 还有 ${p.unallocatedMinutes} 分钟留白，不为填满时间增加动作。`:''}${p.cautions?.length?p.cautions.map(c=>`<br>${esc(c)}`).join(''):''}</span></div>${regionCoverageHTML(p)}<div class="plan-items">${p.items.map((i,index)=>{const a=getActivity(i.activityId);return `<div class="plan-item ${i.status}"><span class="order">${String(index+1).padStart(2,'0')}</span><div class="plan-item-main"><button class="item-title" data-detail="${a.id}">${a.name}</button><p>${goals[a.category]} · ${i.plannedMinutes} 分钟</p>${prescriptionHTML(i,s)}${getNote(s,a.id)?`<div class="mini-note">${icon('bookmark')}${esc(getNote(s,a.id))}</div>`:''}</div><div class="item-actions"><button class="icon-button" data-replace="${i.id}" aria-label="替换${a.name}">${icon('swap')}</button></div></div>`;}).join('')}</div><div class="plan-footer">${ai.ready&&p.source==='ai'?`<div class="ai-adjust"><input id="ai-adjust-text" maxlength="300" value="${esc(ai.adjustText||'')}" placeholder="想怎么调整？例如：换掉引体、再短一点、多练核心" aria-label="调整要求"><button class="secondary" data-action="ai-adjust" ${ai.busy?'disabled':''}>${ai.busy?'调整中…':'调整'}</button></div>`:''}<button class="primary full" data-action="start" ${ai.busy?'disabled':''}>${icon('play')} 开始这次活动</button></div></section>`;
}
// In progress: one focused card at a time; the rest folds into 「看全部」. Rest countdown lives in #rest (app.js).
function runningHTML(s) {
  const p=s.draft,total=p.items.length,done=p.items.filter(i=>i.status==='completed').length;
  const cursor=Math.max(0,Math.min(p.cursor??0,total)),cur=p.items[cursor];
  const no=n=>String(n+1).padStart(2,'0');
  const dots=p.items.map((i,idx)=>`<button class="run-dot ${i.status} ${idx===cursor?'current':''}" data-goto="${idx}" aria-label="第 ${idx+1} 项：${esc(getActivity(i.activityId).name)}"></button>`).join('');
  const top=`<div class="run-top"><div class="run-top-head"><span class="overline">正在进行</span><span class="run-elapsed" id="elapsed">${elapsedText(p.startedAt)}</span><button class="icon-button" data-action="discard" aria-label="结束并撤下安排">${icon('close')}</button></div><div class="run-progress"><div class="run-dots">${dots}</div><span class="run-count">${done} / ${total}</span></div></div>`;
  let card;
  if(cur){
    const a=getActivity(cur.activityId),x=cur.prescription;
    const target=x?[x.sets&&(x.reps||x.seconds)?`${x.sets} 组 × ${x.reps?`${x.reps} 次`:`${x.seconds} 秒`}`:x.sets?`${x.sets} 组`:x.reps?`${x.reps} 次`:x.seconds?`${x.seconds} 秒`:'',x.perSide?'每侧':'',x.load||''].filter(Boolean).join(' · '):'';
    card=`<div class="run-card"><div class="run-order">${no(cursor)} / ${String(total).padStart(2,'0')}</div><button class="item-title run-title" data-detail="${a.id}">${a.name}</button><p class="run-cat">${goals[a.category]}${cur.plannedMinutes?` · 计划 ${cur.plannedMinutes} 分钟`:''}${target?` · 目标 ${esc(target)}`:''}</p>${cur.reason?`<details class="run-why"><summary>为什么推荐</summary><p class="small muted">${esc(cur.reason)}</p></details>`:''}${isTimed(cur,a)?timedCard(cur,s):exerciseLogForm(cur,s)}<div class="run-actions"><button class="secondary" data-skip="${cur.id}">跳过这个动作</button><button class="primary" data-next>下一个 ${icon('arrow')}</button></div></div>`;
  } else {
    const skipped=p.items.filter(i=>i.status==='skipped').length;
    card=`<div class="run-card run-done"><span class="activity-icon strength">${icon('check')}</span><h2>这次都过了一遍</h2><p class="muted">${done} 项已记录${skipped?` · ${skipped} 项跳过`:''}。可以回上面某一项补记，或结束并写下整体感受。</p></div>`;
  }
  const allList=`<details class="run-all"><summary>看全部 ${total} 项 · ${done} 项已记录</summary><div class="run-all-list">${p.items.map((i,idx)=>{const a=getActivity(i.activityId),sets=recordedSetsHTML(i);return `<div class="run-all-row ${i.status} ${idx===cursor?'current':''}"><button class="run-goto" data-goto="${idx}"><span class="order">${i.status==='completed'?icon('check'):no(idx)}</span><span class="run-goto-name">${a.name}<small>${i.status==='skipped'?'已跳过':idx===cursor?'当前':goals[a.category]}</small></span></button><button class="text-button" data-skip="${i.id}">${i.status==='skipped'?'恢复':'跳过'}</button>${sets?`<div class="run-all-sets">${sets}</div>`:''}</div>`;}).join('')}</div></details>`;
  return `<section class="card plan running">${top}${p.pausedForDiscomfort?'<div class="notice error">已记录本次不舒服。请先结束这次活动，不继续增加负荷。</div>':''}${card}${allList}<div class="plan-footer"><button class="primary full" data-action="finish">结束并记下感受 ${icon('arrow')}</button></div></section>`;
}
export function libraryHTML(s,filters) {
  const q=filters.search.trim().toLowerCase();
  const rows=activities.filter(a=>(filters.category==='all'||a.category===filters.category)&&(filters.system==='all'||a.system===filters.system)&&(filters.place==='all'||a.places.includes(filters.place))&&(filters.personal!=='notes'||Boolean(getNote(s,a.id)))&&(filters.personal!=='recent'||s.sessions.some(x=>x.items.some(i=>i.activityId===a.id&&i.status==='completed')))&&`${a.name}${a.aliases.join('')}${a.body.join('')}`.toLowerCase().includes(q));
  const pills=(key,options)=>options.map(([v,l])=>`<button class="pill ${filters[key]===v?'selected':''}" data-${key}="${v}">${l}</button>`).join('');
  return `${heading('YOUR MOVEMENT LIBRARY','找到适合你的动作','不同运动体系，共享一个动作库。你的心得，留在每个动作旁。',`<span class="count-label">${rows.length===activities.length?'':`${rows.length} / `}${activities.length} 个候选</span>`)}<div class="filter-pills"><button class="pill ${filters.personal==='all'?'selected':''}" data-personal="all">全部</button><button class="pill ${filters.personal==='recent'?'selected':''}" data-personal="recent">最近练过</button><button class="pill ${filters.personal==='notes'?'selected':''}" data-personal="notes">有我的心得</button></div><div class="library-toolbar"><label class="search">${icon('search')}<input id="activity-search" placeholder="搜索动作、部位或英文名，如：髋、划船、plank" value="${esc(filters.search)}" aria-label="搜索动作"></label><select id="library-place" aria-label="筛选场地"><option value="all">全部场地</option>${Object.entries(places).map(([v,l])=>`<option value="${v}" ${filters.place===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="filter-pills" role="group" aria-label="筛选训练体系">${pills('system',[['all','全部体系'],...Object.entries(systems)])}</div><div class="filter-pills" role="group" aria-label="筛选能力">${pills('category',[['all','全部能力'],...Object.entries(goals).filter(([k])=>k!=='balanced')])}</div><div class="activity-grid">${rows.map(a=>`<button class="activity-card" data-detail="${a.id}"><div class="activity-card-top"><span class="activity-icon ${a.category}">${icon(a.category)}</span><span class="small muted">${a.selectable===false?'仅供浏览':a.level?`第 ${a.level} 式 · ${tiers[a.tier]}`:esc(a.difficulty)}</span></div><h3>${a.name}</h3><p>${esc(a.description)}</p><div class="tags">${badge(systems[a.system])}${badge(goals[a.category])}${badge(a.equipment.length?a.equipment.map(e=>equipmentLabels[e]).join(' / '):'无器械')}</div><div class="activity-card-bottom"><span>${a.body.join(' · ')}</span>${getNote(s,a.id)?`<span class="note-indicator">${icon('bookmark')} 有心得</span>`:icon('chevron')}</div></button>`).join('')||empty('没有找到对应动作','试试其他部位或筛选条件。')}</div><p class="prototype-note">候选库尚未完成专业审核；仅供浏览的动作不会进入自动安排，高级动作只在训练经历为「有规律训练」时安排。</p>`;
}
export function recordsHTML(s,ai={}) {
  return `${heading('EVERY SESSION COUNTS','留下身体的进步','练过什么、当时的感受，都在这里。',`<div class="heading-actions">${ai.ready?`<button class="primary" data-action="ai-log">${icon('plus')} 粘贴记录，AI 整理</button>`:''}<button class="secondary" data-action="manual-log">手动补记</button><button class="secondary" data-action="import">恢复备份</button><button class="secondary" data-action="export">${icon('download')} 导出记录</button></div>`)}${s.sessions.length?`<div class="timeline">${[...s.sessions].reverse().map(s=>`<button class="session-card card" data-session="${s.id}"><div class="session-date"><strong>${dateText(s.endedAt,{day:'numeric'})}</strong><span>${dateText(s.endedAt,{month:'long'})}</span></div><div class="session-info"><h3>${s.planSnapshot?`${planFocus(s.planSnapshot.request)} · ${places[s.planSnapshot.request.place]}`:'补记的训练'}</h3><p>${s.items.filter(i=>i.status==='completed').map(i=>esc(i.activitySnapshot?.name || getActivity(i.activityId)?.name || i.customName || i.activityId)).join('、')}</p><span>${s.actualMinutes==null?'未填写实际时长':`${s.actualMinutes} 分钟`}${s.effort?` · 费力程度 ${s.effort}/10`:''}</span>${s.feedback?`<div class="session-quote">“${esc(s.feedback)}”</div>`:''}</div>${icon('chevron')}</button>`).join('')}</div>`:`<section class="card">${empty('第一条记录，等你开始','完成一次训练后，确认的动作和感受会自动出现在这里。',`<button class="primary" data-nav="today">安排今天的活动 ${icon('arrow')}</button>`)}</section>`}<section class="section"><div class="section-heading"><h2>身体随记</h2><button class="text-button" data-action="observation">${icon('plus')} 记一笔</button></div>${s.observations.length?`<div class="observation-list">${[...s.observations].reverse().map(o=>`<article class="card observation"><span class="overline">${dateText(o.createdAt)}</span><p>${esc(o.text)}</p><span class="small muted">个人感受 · 尚未进行专业评估</span></article>`).join('')}</div>`:'<p class="muted">暂时没有身体随记。睡眠、疲劳或不适，都可以记录在这里。</p>'}</section>`;
}
export function knowledgeHTML(s,filter) {
  const rows=s.knowledge.filter(k=>filter==='all'||k.status===filter);
  const captureFor=k=>(s.captures||[]).find(c=>c.knowledgeId===k.id);
  return `${heading('COLLECT · THINK · PRACTICE','让好想法留下来','把收藏变成理解，再变成对自己有用的练习。',`<button class="primary" data-action="capture">${icon('plus')} 收藏一条分享</button>`)}<div class="capture-banner">${icon('link')}<div><h3>刷到一个想试的动作？</h3><p>粘贴链接和文案，先进入收件箱；AI 只根据你提供的文字整理，不会猜视频内容。</p></div><button class="icon-button" data-action="capture" aria-label="收藏一条分享">${icon('plus')}</button></div><div class="filter-pills">${[['all','全部内容'],['inbox','待整理'],['saved','已收进个人库']].map(([v,l])=>`<button class="pill ${filter===v?'selected':''}" data-knowledge-filter="${v}">${l}</button>`).join('')}</div><div class="knowledge-grid">${rows.map(k=>{const c=captureFor(k),claims=Array.isArray(k.claims)?k.claims:[];return `<article class="card knowledge-card"><div class="section-heading">${badge(k.status==='inbox'?'待整理':'个人知识卡',k.status==='inbox'?'warm':'')}<button class="icon-button" data-edit-knowledge="${k.id}" aria-label="编辑${esc(k.title)}">${icon('edit')}</button></div><h3>${esc(k.title)}</h3><p>${esc(k.text)}</p>${claims.length?`<details><summary>查看 ${claims.length} 条来源依据</summary>${claims.map(x=>`<p>${esc(x.text)}<br><span class="small muted">原文：「${esc(x.evidenceQuote)}」</span></p>`).join('')}</details>`:''}<div class="tags">${k.activityIds.map(id=>`<button class="badge" data-detail="${id}">${esc(getActivity(id)?.name||id)}</button>`).join('')}</div><div class="knowledge-source">${icon('bookmark')} ${esc(k.sourceTitle||'我的收藏')}${c?.shareText?' · 有来源文字':' · 待补充来源文字'}</div><footer>${safeURL(k.url)?`<a class="text-button" href="${esc(safeURL(k.url))}" target="_blank" rel="noopener noreferrer">打开原文 ${icon('arrow')}</a>`:'<span class="small muted">保留原始思考</span>'}${k.useInPlanning?'<span class="badge">允许推荐参考</span>':''}${c?(c.shareText?`<button class="text-button orange" data-analyze-capture="${c.id}">AI 整理 ${icon('arrow')}</button>`:`<button class="text-button orange" data-edit-capture="${c.id}">补充内容 ${icon('edit')}</button>`):k.status==='inbox'?`<button class="text-button orange" data-save-knowledge="${k.id}">收进个人库 ${icon('check')}</button>`:''}</footer></article>`;}).join('')||empty('这里还没有内容','收藏一条分享，或换一个分类。')}</div><p class="prototype-note">来源文字、AI 整理和你的编辑都会保留在本机。链接本身不会被自动读取或当作视频证据。</p>`;
}
export function bodyHTML(s) {
  const p=s.profile;
  return `${heading('GET TO KNOW YOURSELF','认识身体，慢慢来','从你知道的情况开始，不必一次填写完整。')}<div class="profile-grid"><form id="profile-form" class="card profile-form"><h2>我的基本设置</h2><label>怎么称呼你<input name="name" value="${esc(p.name)}" maxlength="30" placeholder="你的称呼（可选）"></label><div class="field-row"><label>当前训练经历<select name="experience"><option value="beginner" ${p.experience==='beginner'?'selected':''}>刚开始 / 重新开始</option><option value="regular" ${p.experience==='regular'?'selected':''}>有规律训练经历</option></select></label><label>默认训练重点<select name="focus">${Object.entries(goals).map(([v,l])=>`<option value="${v}" ${p.focus===v?'selected':''}>${l}</option>`).join('')}</select></label></div><label class="check-pill wide"><input type="checkbox" name="skipWarmup" ${p.skipWarmup?'checked':''}><span>不习惯热身，直接开练（自动安排时跳过热身与放松）</span></label><div class="field-row"><label>年龄段（可选）<select name="ageRange">${[['','暂不填写'],['under18','未满18岁'],['18-39','18–39岁'],['40-64','40–64岁'],['65+','65岁及以上']].map(([v,l])=>`<option value="${v}" ${p.ageRange===v?'selected':''}>${l}</option>`).join('')}</select></label><label>常参与的运动<input name="preferredSports" maxlength="200" value="${esc(p.preferredSports||'')}" placeholder="例如：羽毛球、跑步"></label></div><div class="field-row"><label>平均睡眠（小时，可选）<input name="sleepHours" type="number" min="0" max="24" step="0.5" value="${p.sleepHours??''}"></label><label>日均久坐（小时，可选）<input name="sittingHours" type="number" min="0" max="24" step="0.5" value="${p.sittingHours??''}"></label></div><label>最近想改善什么<textarea name="goalText" placeholder="例如：工作间隙多活动；提高羽毛球步伐协调性" maxlength="2000">${esc(p.goalText)}</textarea></label><fieldset><legend>我可以使用的器械</legend><div class="equipment-checks">${Object.entries(equipmentLabels).map(([v,l])=>`<label class="check-pill"><input type="checkbox" name="equipment" value="${v}" ${p.equipment.includes(v)?'checked':''}><span>${l}</span></label>`).join('')}</div></fieldset><label>需要留意的身体情况<textarea name="bodyNotes" placeholder="可选：既往受伤、近期不适、专业人员给出的限制……" maxlength="4000">${esc(p.bodyNotes)}</textarea></label><p class="helper left">此处文字仅作为档案保存。程序不会把自然语言病史当作已完成医学评估；填写限制后，本地规则与 AI 都会暂停自动安排，供进一步评估。</p><button class="primary" type="submit">保存我的设置 ${icon('check')}</button></form><aside>${capacityHTML(s)}${privacyHTML(s)}</aside></div>`;
}
